### ISSUE TITLE
地址填错了，点击删除无效。刷新了也还在

### ISSUE THREAD

**Issue by qingweiSun** [sub-store-org/Sub-Store#136]
![telegram-cloud-document-5-6181406568370669023](https://user-images.githubusercontent.com/16513906/175857938-ab4e507c-577f-41f9-969f-61f258487097.jpg)

**Comment by Peng-YM** [comment]
发一下日志看看

**Comment by qingweiSun** [comment]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/16513906/175877152-bd55b2d1-d80f-4a1c-8afd-33d5b7187227.png">
这个么

**Comment by Peng-YM** [comment]
请尝试使用以下脚本清除缓存

https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/scripts/revert.js
