### ISSUE TITLE
TAG 斯里兰卡🇱🇰节点匹配国旗错误

### ISSUE THREAD

**Issue by bunizao** [sub-store-org/Sub-Store#142]
大概是这样❤️![image](https://user-images.githubusercontent.com/102936102/178154714-2f7f25dd-e729-42e9-996c-998416089303.png)

**Comment by bunizao** [comment]
妈的 图放错了😅![image](https://user-images.githubusercontent.com/102936102/178154697-22b549f1-60ef-44b9-8b97-c3167ec7537f.png)

**Comment by VirgilClyne** [comment]
🥹🥹

**Comment by xaver985** [comment]
TAG又加了个库拉索🇨🇼节点🧐

**Comment by VirgilClyne** [comment]
> TAG又加了个库拉索🇨🇼节点🧐

还有没有其他缺少的，我一并添加

**Comment by xaver985** [comment]
> > TAG又加了个库拉索🇨🇼节点🧐
> 
> 还有没有其他缺少的，我一并添加

没了，目前就这俩

**Comment by bunizao** [comment]
🍟❤️

**Comment by bunizao** [comment]
TAG新增 🇺🇿 乌兹别克斯坦 节点
国家代号 UZ

**Comment by bunizao** [comment]
又新增了一个老挝🇱🇦节点😅

**Comment by Peng-YM** [comment]
建议使用 IP-Flag 脚本统一处理类似的国旗
