### ISSUE TITLE
添加个：脚本订阅的功能看看有无必要

### ISSUE THREAD

**Issue by gugu33** [sub-store-org/Sub-Store#143]
现在脚本操作这项功能用的比较多，也已经有很多大佬贡献了多少好多实用脚本。
但每次添加都很麻烦，需要把链接找出来填上。能否像订阅一样把大佬的脚本先订阅上。然后脚本操作里面选链接后，只要再给出列表进行选择就行了。
以上

**Comment by Peng-YM** [comment]
已经在考虑类似的功能需求～
