### ISSUE TITLE
Justmysocks机场的两条ss线路未识别出来

### ISSUE THREAD

**Issue by Chellphe** [sub-store-org/Sub-Store#145]
一共有6条线路，4条vmess，2条ss，添加后只显出了4条vmess，还有两条ss不在了

**Comment by donniean** [comment]
+1

**Comment by DesnLee** [comment]
> 一共有6条线路，4条vmess，2条ss，添加后只显出了4条vmess，还有两条ss不在了

方便的话订阅发给我看看

**Comment by donniean** [comment]
> 

我可以提供的，请问怎么联系你？

**Comment by DesnLee** [comment]
> > > 一共有6条线路，4条vmess，2条ss，添加后只显出了4条vmess，还有两条ss不在了
> 
> > 
> 
> > 方便的话订阅发给我看看
> 
> 
> 
> 我可以提供的，请问怎么联系你？ @DesnLee 

cool scripts 群里

**Comment by donniean** [comment]
> > > > 一共有6条线路，4条vmess，2条ss，添加后只显出了4条vmess，还有两条ss不在了
> > 
> > 
> > > 
> > 
> > 
> > > 方便的话订阅发给我看看
> > 
> > 
> > 我可以提供的，请问怎么联系你？ @DesnLee
> 
> cool scripts 群里

电报群吗

**Comment by DesnLee** [comment]
> > > > > 一共有6条线路，4条vmess，2条ss，添加后只显出了4条vmess，还有两条ss不在了
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 方便的话订阅发给我看看
> > > 
> > > 
> > > 我可以提供的，请问怎么联系你？ @DesnLee
> > 
> > 
> > cool scripts 群里
> 
> 电报群吗

是的
