### ISSUE TITLE
圈X怎么玩，有没有教程指导一下

### ISSUE THREAD

**Issue by lrs95** [sub-store-org/Sub-Store#147]

**Comment by wcjxixi** [comment]
### 搭建本地 https 服务器
编辑 Quantumult X 的配置文件，在对应的部分添加以下配置：

```
[rewrite_local]
^https?:\/\/sub\.store url script-analyze-echo-response https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/backend/sub-store.min.js

[mitm]
# 添加一个 sub.store 域名
hostname=sub.store
simple_cert_hostname=sub.store
```

使用 Safari 打开 [https://sub.store/](https://sub.store/)，如网页正常打开并且未弹出任何错误提示，说明 Sub-Store 已经配置成功。可以把 Sub-Store 添加到主屏幕，即可获得类似于 APP 的使用体验。

### 添加原始订阅并个性化节点、配置同步等

见官方教程

### 将转换后的订阅添加到 Quantumult X
「同步」选项卡中点「复制」，将复制的配置链接添加到 Quantumult X 的配置文件的 [server_remote] 下方。

### 使用 iOS 的快捷指令自动化同步到 Gist
获取 Sub-Store 自动同步[快捷指令](https://www.icloud.com/shortcuts/cfe17d8ef9ab44b2b7ab1bc7be30efa3)。可以配合自动化使用，例如每天晚上十二点自动同步。

### 需要注意的地方
「同步」选项卡中的「同步配置」的「配置名称」中不能使用中文，否则获取的配置链接会不正确。
