### ISSUE TITLE
用订阅获取ss节点出错

### ISSUE THREAD

**Issue by yuhangrao** [sub-store-org/Sub-Store#151]
订阅中ss节点的加密方式为xchacha20-ietf-poly1305时节点信息获取会出错，表现为查看surge的节点信息，字段显示为encrypt-method=undefined，实测将加密方式换成aes-128-gcm能正常获取，正常显示为encrypt-method= aes-128-gcm

**Comment by Peng-YM** [comment]
Surge 已经支持这种加密方式了吗

**Comment by yuhangrao** [comment]
> Surge 已经支持这种加密方式了吗

支持，我一直在用

**Comment by Peng-YM** [comment]
已解决
