### ISSUE TITLE
脚本操作当节点数量超过52～53左右时，以后的节点将不再操作

### ISSUE THREAD

**Issue by XUYinong** [sub-store-org/Sub-Store#153]
我试图将节点中的英文国名转换为三位国家英文代码
如🇺🇸 United States 转为 🇺🇸 USA, 但是发现只处理了前52～53个节点，以后并未处理；而将节点顺序颠倒也是同样的问题。
使用QX最新商店版

**Comment by XUYinong** [comment]
还有一个请求能否复制订阅，这样不同订阅，但是相同的节点操作不用再全部重新设置一遍

**Comment by Peng-YM** [comment]
截图看一下substore配置

**Comment by XUYinong** [comment]
> 截图看一下substore配置

![39F0EEEF-97A9-42CF-AD8A-5125200392B6](https://user-images.githubusercontent.com/79797050/183004495-611d5a0a-5dff-4b53-a0f8-ecc719c18a91.jpeg)
Duplicate of #

**Comment by XUYinong** [comment]
经过排查发现不是上述问题，亦不是此项目引起的问题
