### ISSUE TITLE
下载更新出错

### ISSUE THREAD

**Issue by horaynia** [sub-store-org/Sub-Store#158]
在sub里配置好后，在surge端更新外部资源的时候显示超时，但是sub可以正常访问，也能访问对应节点信息。同时同一机场的其他的配置可以正常更新（比如我分别筛选了香港去国旗，新加坡去国旗等，新加坡那个可以在surge里正常下载更新，但是香港的不行，我在sub里能打开香港的预览）
![9EFC2AB6-92F8-4B37-8501-5EAF65F0DE1E](https://user-images.githubusercontent.com/50537627/184060703-1af2fa1e-5076-4de4-b712-45612ce4cf28.png)

**Comment by Peng-YM** [comment]
应该是网络问题
