### ISSUE TITLE
节点obfs-host的网址带：的无法读取

### ISSUE THREAD

**Issue by abingx** [sub-store-org/Sub-Store#160]
我有一个订阅，节点的格式如下
台湾 TW 01 = ss, xxxx.xxxxx.top, 15551, encrypt-method=chacha20-ietf, password=xxxxx, obfs=http, obfs-host=178f219673.microsoft.com:, udp-relay=true
因为obfs-host网址是178f219673.microsoft.com:，有这个：就读不出来节点，删除：可以正常读取

**Comment by Peng-YM** [comment]
此格式不合法

**Comment by hy-cs** [comment]
不了解格式是否有问题，但是Surge上使用机场提供的节点，如果obfs-host如果没有: 是连不上的，而且sub-store导入对应订阅读不出来节点
