### ISSUE TITLE
新建单条订阅 - 名称链接填完之后- 添加一个操作 - 国旗操作 - 第二个不管选什么都是国旗操作

### ISSUE THREAD

**Issue by xiky** [sub-store-org/Sub-Store#161]
surge 
![photo_2022-08-18 22 48 21](https://user-images.githubusercontent.com/17621199/185424875-d63c1896-c3ec-4ae9-b6d1-e145a716272f.jpeg)

**Comment by DesnLee** [comment]
picker滑倒要选的稍等半秒钟 等滚动动画结束再确定

**Comment by xiky** [comment]
了解了~
