### ISSUE TITLE
vmess+http圈X转换失败!

### ISSUE THREAD

**Issue by tanzl** [sub-store-org/Sub-Store#162]
❚  [sub-store] ERROR: Cannot produce proxy: {
  "server": "xxx.xx.xx.xxx",
  "port": 443,
  "cipher": "chacha20-poly1305",
  "uuid": "8b319hgj-57e0-46f5-a5af-069c93b165ad",
  "tfo": true,
  "udp": true,
  "name": "香港7-tcp",
  "type": "vmess",
  "alterId": 0,
  "network": "http",
  "http-opts": {
    "headers": {
      "Host": [
        "puui.qpic.cn"
      ]
    }
  }
}
Reason: TypeError: undefined is not an object (evaluating 't["ws-opts"].path')

**Comment by tanzl** [comment]
qx.js 209行是否应该放在201行内?

**Comment by tanzl** [comment]
[这里写死ws-opts了](https://github.com/sub-store-org/Sub-Store/blob/0072739f0154eca36d8b3731c59b319ecf02ff06/backend/src/core/proxy-utils/producers/qx.js#L209)
```javascript
appendIfPresent(`,obfs-uri=${proxy['ws-opts'].path}`, 'ws-opts.path');
```
应该改成
```javascript
appendIfPresent(`,obfs-uri=${proxy[`${proxy.network}-opts`].path}`, `${proxy.network}-opts.path`);
```

**Comment by Peng-YM** [comment]
已修复
