### ISSUE TITLE
订阅无法删除

### ISSUE THREAD

**Issue by tangjunhua1993** [sub-store-org/Sub-Store#163]
删除报错：
Failed to delete artifact 123

type: InternalServerError

Reason: ERROR: Validation Failed   

同步报错：
Failed to sync all artifacts

type: InternalServerError

Reason: TypeError: undefined is not an object (evaluating '(i=(0,_$database_100.findByName)(a,n)).source')

请问这个是什么问题

**Comment by winx402** [comment]
同样报错，删除和同步都是

Failed to delete artifact 123

type: InternalServerError

Reason: ERROR: Validation Failed

**Comment by winx402** [comment]
![image](https://user-images.githubusercontent.com/10544631/186943068-52986cfb-33a5-4f73-8647-5f3f8c38d668.jpeg)

**Comment by htmcssjs** [comment]
可以通过修改gist.github.com里面的同步配置 然后sub-store里面-我的-下载 覆盖本地就行了 注意gist文件的格式（多了逗号之类的） 格式错误的话 就需要清除sub-store缓存（https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/scripts/revert.js ）

**Comment by DesnLee** [comment]
gist 手动创建一个同名的文件，再来删除。或者先同步上去，再删除

**Comment by DesnLee** [comment]
> gist 手动创建一个同名的文件，再来删除。或者先同步上去，再删除

如果都不行，查看token是否有效

**Comment by winx402** [comment]
目前已经好了，但是不是确定通过什么样的方式。
之前试了很多方式，token重新申请，sub_store的gist删除，重新创建。甚至申请了一个新的github账号都不行。
一直持续了十几天，后来有一次突然重试就好了，到现在一直没有问题了。
不确定原因。

**Comment by tangjunhua1993** [comment]
无法同步的原因，是由于我节点协议是ssr我转换成surge就不能同步，更换SS协议可以正常同步；删除订阅后面通过在gist创建一个同名文件就可以删除了。我造成这个的原因貌似是我把gist的仓库都给删了所以导致后面无法删除，后面更换了token 重新同步创建同名文件删除。

**Comment by tangjunhua1993** [comment]
还是无法删除的，substore有个电报群。群里有人发清空substore的缓存脚本，可以尝试。我没试过不折腾了

**Comment by winx402** [comment]
> token

貌似是这个ssr 转换的原因，导致不能同步。只是不能不同的错误信息有点看不出来

**Comment by Soizzer** [comment]
> 可以通过修改gist.github.com里面的同步配置 然后sub-store里面-我的-下载 覆盖本地就行了 注意gist文件的格式（多了逗号之类的） 格式错误的话 就需要清除sub-store缓存（https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/scripts/revert.js ）

请问surge要如何使用这个脚本来清除缓存？在surge的脚本模块添加远程脚本时，提示参数无效。可以指导下详细的方法吗？

**Comment by Soizzer** [comment]
> 可以通过修改gist.github.com里面的同步配置 然后sub-store里面-我的-下载 覆盖本地就行了 注意gist文件的格式（多了逗号之类的） 格式错误的话 就需要清除sub-store缓存（https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/scripts/revert.js ）

还有请教如何修改gist.github.com里的同步配置？是点击同步页面右上角的小眼睛图标打开的github页面吗？但我打开后，显示的是404页面…
![Uploading 2995FBBF-4440-42D7-AED4-3F18F502B748.png…]()

**Comment by Soizzer** [comment]
![A3C9E2F1-F4E2-40F6-9969-62C86B35765C](https://user-images.githubusercontent.com/73036854/188788066-4399755d-a72f-498a-82a4-9d8887eb5ea7.png)
点击同步页面右上角的小眼睛图标打开的github页面吗？但我打开后，显示的是404页面…
