### ISSUE TITLE
surge 更新后 无法正常访问 一片空白

### ISSUE THREAD

**Issue by hlf2016** [sub-store-org/Sub-Store#165]
surge 更新最新正式版后 
https://sub-store.vercel.app/ 无法访问 手机端变现为白屏。

电脑端 ping sub-store.vercel.app 也是超时

<img width="764" alt="image" src="https://user-images.githubusercontent.com/24551738/187178881-dbbf57c1-1364-4942-a84e-37825fa0f9b8.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/24551738/187179066-ec87441e-2fd6-4f70-b6e9-47ab58f98598.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/24551738/187179221-f1fa4ad1-1302-4ee4-9d52-60e47087b6d7.png">

**Comment by Peng-YM** [comment]
vercel.app 已经被墙了，需要手动添加规则
