### ISSUE TITLE
部分 port 解析不出来

### ISSUE THREAD

**Issue by uclort** [sub-store-org/Sub-Store#167]
{"v":"2","ps":"Amazon","add":"1.2.1.1","port":"21","id":"6d6f868","aid":"0","net":"tcp","type":"none","host":"","path":"","tls":""}

port 为 21 或 23 的节点信息都解析不出来，预览 surge 的时候看到是 undefined

**Comment by uclort** [comment]
https://github.com/sub-store-org/Sub-Store/blob/0072739f0154eca36d8b3731c59b319ecf02ff06/backend/src/core/proxy-utils/parsers/peggy/qx.js#L131

看了一下源码，请问是这个地方限制的端口号区间吗？代码限制的 80...65535，80以内的请问是有什么问题么？

@Peng-YM

**Comment by DesnLee** [comment]
> https://github.com/sub-store-org/Sub-Store/blob/0072739f0154eca36d8b3731c59b319ecf02ff06/backend/src/core/proxy-utils/parsers/peggy/surge.js#L110-L115
> 
> 看了一下源码，请问是这个地方限制的端口号区间吗？代码限制的 80...65535，80以内的请问是有什么问题么？
> 
> @Peng-YM

建议从30000以后开始用，wiki查查常用端口，避开他们

**Comment by uclort** [comment]
> > https://github.com/sub-store-org/Sub-Store/blob/0072739f0154eca36d8b3731c59b319ecf02ff06/backend/src/core/proxy-utils/parsers/peggy/surge.js#L110-L115
> > 
> > 看了一下源码，请问是这个地方限制的端口号区间吗？代码限制的 80...65535，80以内的请问是有什么问题么？
> > @Peng-YM
> 
> 建议从30000以后开始用，wiki查查常用端口，避开他们

感谢回答。
所以这个区间其实只是一个大家默认的一个相对的区间是吧？
不是因为一些特别的原因的话我就没疑问了，我以为 80 以下的端口是会造成一些什么样的问题。

**Comment by Peng-YM** [comment]
80以下的端口一般是操作系统保留使用的，所以一般不会是代理端口

**Comment by Peng-YM** [comment]
已经放开这个限制了
