### ISSUE TITLE
mac端怎么样才能关闭订阅同步通知

### ISSUE THREAD

**Issue by AndyandAndy00** [sub-store-org/Sub-Store#168]
sub-store订阅同步的时候surge for mac会弹出通知提醒，怎么样才能单独关掉这个提醒

**Comment by Peng-YM** [comment]
目前没有关闭这个通知的开关

**Comment by AndyandAndy00** [comment]
> 目前没有关闭这个通知的开关

好的，谢谢您的回复，希望未来能增加这样的一个开关
