### ISSUE TITLE
如何修改Gist？点击小眼睛打开是404页面

### ISSUE THREAD

**Issue by Soizzer** [sub-store-org/Sub-Store#169]
请问如何修改gist.github.com里的同步配置？是点击同步页面右上角的小眼睛图标打开的github页面吗？
![B5532556-30F0-40C3-B6B4-8B6FF6CAE175](https://user-images.githubusercontent.com/73036854/189161404-acf400b6-74a2-44fd-b522-dca4191d586a.png)
但我打开后，显示的是404页面…

**Comment by Peng-YM** [comment]
点击一下主页的刷新按钮就可以刷新 gist 的地址了
