### ISSUE TITLE
本地订阅是否能支json格式

### ISSUE THREAD

**Issue by nitmali** [sub-store-org/Sub-Store#173]
本地订阅相关文档说明目前不明确
是否能支json格式

**Comment by xream** [comment]
@nitmali
1. 按代理 app 文件配置一行一个节点
2. 使用 clash 系配置一个合法的远程代理集 YAML/JSON(包含 proxies 字段)

**Comment by Peng-YM** [comment]
本地订阅随意按照 Loon, QX, Surge 的订阅格式书写节点即可
