### ISSUE TITLE
Error Alert on Syncing to Local

### ISSUE THREAD

**Issue by shindgewongxj** [sub-store-org/Sub-Store#174]
There may be syntax errors while modifying sub-store gist in text editor and then commit. If you tap `Download` to local in sub.store, the config with errors would be loaded and make whole sub-store stop working and to solve that reset proxy tool is needed. Is it possible to test after downloading before loading?  If an error was found, then stop loading to keep Sub-Store working.

在编辑Sub-Store gist过程中可能有书写错误，此时下载将把同步错误gist加载到本地导致整个sub-store出现错误无法使用，只能通过重置网络调试工具解决。那么，可以在加载时检测gist是否存在错误吗？如检测到错误则不加载以保证sub-store在正确状态下运行。

**Comment by Peng-YM** [comment]
感谢提议，后续会加上这个提示

**Comment by xream** [comment]
77191f9 should be enough for now
