### ISSUE TITLE
snell v4 无 obfs 参数异常

### ISSUE THREAD

**Issue by ocd0711** [sub-store-org/Sub-Store#176]
snell v4 无 obfs 参数异常, substore 解析不出 snell 节点

ex: snell-test = snell, xxxxx, xxxx, psk=xxxx, version=4, tfo=true

**Comment by Peng-YM** [comment]
暂未支持 snell v4 版本

**Comment by xream** [comment]
@ocd0711 2.14.4+ 已经支持了
