### ISSUE TITLE
无法提取SS节点

### ISSUE THREAD

**Issue by lge6** [sub-store-org/Sub-Store#177]
同一个订阅连接下有vmess和SS节点，但是SS节点无法提取，vmess节点正常；
单独放SS节点结果也是空白。

**Comment by snowdegit** [comment]
> 同一个订阅连接下有vmess和SS节点，但是SS节点无法提取，vmess节点正常；
> 
> 单独放SS节点结果也是空白。

同问

**Comment by Elvislanpop** [comment]
Shadowsocks sever 生成的 URL默认为 ss://Base64(method:password@server:port) Sub-Store无法识别
你可以尝试 
ss:Base64(method:password)@server:port
进行转换

**Comment by Elvislanpop** [comment]
> 同一个订阅连接下有vmess和SS节点，但是SS节点无法提取，vmess节点正常； 单独放SS节点结果也是空白。

Shadowsocks sever 生成的 URL默认为 ss://Base64(method:password@server:port) Sub-Store无法识别
你可以尝试
ss:Base64(method:password)@server:port
进行转换
