### ISSUE TITLE
Shadowrocket 模块无法加载出刷新按钮和➕按钮

### ISSUE THREAD

**Issue by seirhsiao** [sub-store-org/Sub-Store#178]
https://user-images.githubusercontent.com/14857002/202720906-15a7fec0-4c5e-44fa-945a-89ff085f9b0c.MOV

![image](https://user-images.githubusercontent.com/14857002/202720949-bc58423d-bbbf-4abd-ad33-b927d1fa7d5e.jpeg)

![image](https://user-images.githubusercontent.com/14857002/202720986-59ae36e6-d272-4b3a-842c-2c4b5ca7c611.jpeg)

**Comment by Peng-YM** [comment]
已知问题，是小火箭的bug，对同一个域名的两个重写只能触发一个

**Comment by seirhsiao** [comment]
好的，明白，谢谢答复
