### ISSUE TITLE
在Stash Sub-Store的单条订阅，无法新增VLESS节点，可以新增VMESS节点

### ISSUE THREAD

**Issue by aadenyihongchen** [sub-store-org/Sub-Store#179]
尝试在在Stash Sub-Store的单条订阅，无法新增VLESS节点，可以新增VMESS节点。
同样的单条订阅在Shadowrocket也一样，无法新增VLESS节点，可以新增VMESS节点。
在Stash/Shadowrocket里，单独新增VLESS节点可正常使用。

**Comment by toyo2333** [comment]
这个有结论了么？
