### ISSUE TITLE
可不可以支持一下导出v2ray订阅

### ISSUE THREAD

**Issue by Infatuation-Fei** [sub-store-org/Sub-Store#180]
同步订阅希望支持v2ray格式的，同步到gist让v2rayN也可以订阅

**Comment by xream** [comment]
🆕 `target` 为 `V2Ray`

**Comment by Infatuation-Fei** [comment]
> 🆕 `target` 为 `V2Ray`

![IMG_4465](https://github.com/sub-store-org/Sub-Store/assets/58471624/26e3ea59-803d-48f4-bee4-b453e32a8b37)
同步订阅这里似乎还没有v2ray的选项？

**Comment by xream** [comment]
那个前端需要 peng 佬部署才行. 可以先用我的前端 https://sub-store-xream.pages.dev 或 https://sub-store.zhetengsha.eu.org
