### ISSUE TITLE
前后端连接可否改用http

### ISSUE THREAD

**Issue by JGan678** [sub-store-org/Sub-Store#181]
虽然这个项目设计前后端可以运行在任何位置，但针对的主要应用场景是本地通过脚本覆写sub.store的响应，实现后端功能。这样的话所有请求都在本地完成，是否加密对安全性没有影响，而且surge在多个设备上配置证书非常麻烦，如果前端可以默认使用http，就只需安装模块并打开覆写与脚本，极大简化初次配置过程。

**Comment by Peng-YM** [comment]
使用 https 是因为前端托管在 vercel 上，根据web标准，vercel 作为一个 https 的站点，前端只能支持发送 https 请求
