### ISSUE TITLE
同步订阅到gist的链接粘贴到loon无法显示流量信息

### ISSUE THREAD

**Issue by LimeAroma** [sub-store-org/Sub-Store#184]
订阅节点的流量信息是用节点显示的，但是同步订阅到gist后在loon里面添加则没有流量显示

**Comment by xream** [comment]
额 当时好像回复错了 可能是用来显示流量的节点被 `过滤非法节点` 给过滤掉了或者是其他什么原因...

FYI: 2.14.82 更新了

脚本操作增加流量信息操作 `flowUtils`

流量信息操作用法: 参考 https://t.me/zhetengsha/948
