### ISSUE TITLE
tls-alpn参数无法解析

### ISSUE THREAD

**Issue by tonyyqq** [sub-store-org/Sub-Store#188]
Quantumult X 1.0.31版本允许自定义所有基于 TLS 代理协议的 TLS Client Hello ALPN 项 - 例如：tls-alpn=02:68:32:08:68:74:74:70:2f:31:2e:31 代表 Client Hello 中 ALPN 为 h2 及 http/1.1 即 {2, 'h', '2', 8, 'h', 't', 't', 'p', '/', '1', '.', '1'}

此参数无法被Sub-Store解析

**Comment by xream** [comment]
2.14.86 应该支持了
