### ISSUE TITLE
怎么在openwrt docker等服务端安装呢？

### ISSUE THREAD

**Issue by llity** [sub-store-org/Sub-Store#189]
希望提供更多安装方法。谢谢

**Comment by xream** [comment]
参考 https://xream.notion.site/Node-js-render-fork-3334b3943c4f4671b25a24908613e63d

**Comment by Asakushen** [comment]
> 参考 https://xream.notion.site/Node-js-render-fork-3334b3943c4f4671b25a24908613e63d

您好链接失效了，关闭了公开？同样有openwrt docker内部署需求

**Comment by xream** [comment]
@Asakushen render 限制太多 原文章我关了 教程请看 https://xream.notion.site/Sub-Store-abe6a96944724dc6a36833d5c9ab7c87
