### ISSUE TITLE
机场订阅链接转换后在cfw里Proxies为空

### ISSUE THREAD

**Issue by data7799** [sub-store-org/Sub-Store#191]
今天在pc成功搭建了Sub Store,转换订阅(只进行了添加国旗操作)后预览，一切正常。在cfw里下载，提示成功，但是切换到Proxies里却是空的。试了两个机场链接都一样。
![image](https://user-images.githubusercontent.com/15697784/213375481-23fb7a49-74ca-4e05-955f-5416bacb5513.png)

**Comment by data7799** [comment]
右键该配置点击edit,发现缺失port,socks-port,allow-lan,mode,log-level,external-controller等信息，取而代之的是0-n的节点信息，下面proxy-groups为空

**Comment by Space-Loon** [comment]
> 右键该配置点击edit,发现缺失port,socks-port,allow-lan,mode,log-level,external-controller等信息，取而代之的是0-n的节点信息，下面proxies和proxy-groups为空，

你好，解决了嘛？解决了的话麻烦问一下怎么导入的？

**Comment by data7799** [comment]
你好，没有解决，已经用了订阅转换网站
