### ISSUE TITLE
同时包含SS和Vmess的订阅，转换后只剩下Vmess订阅

### ISSUE THREAD

**Issue by GaiZhenbiao** [sub-store-org/Sub-Store#195]
我使用JustMySocks机场，其订阅链接为SS格式（Base64解码后为6条订阅URL），其中有4条Vmess节点，2条SS节点。但是，使用Sub-Store转换后，就只剩下Vmess节点了。软件UI中并没有相关选项（那些选项我都保持默认了）。经测试，subconverter并没有这个问题，所以这应该是Sub-Store的bug。

**Comment by snowdegit** [comment]
我有同样的问题

**Comment by 0x5826** [comment]
同问题

**Comment by lge6** [comment]
> 

跟你的问题一样

**Comment by oyhngithub** [comment]
有同样的问题

**Comment by xream** [comment]
上面的朋友时间太久远了我就不找了 @oyhngithub 私我订阅我看看？可在测试之后重置订阅 tg @xream

**Comment by oyhngithub** [comment]
> 上面的朋友时间太久远了我就不找了 @oyhngithub 私我订阅我看看？可在测试之后重置订阅 tg @xream

https://jmssub.net/members/getsub.php?service=763538&id=709d2110-0311-4980-894a-1be81c50ccc8

**Comment by xream** [comment]
@GaiZhenbiao @snowdegit @0x5826 @lge6 @oyhngithub 麻烦测试一下 最新的 2.14.8 应该可以了

**Comment by oyhngithub** [comment]
可以啦 赞

**Comment by 0x5826** [comment]
实际测试可以了！
