### ISSUE TITLE
surge ios 端/Mc，导入 sub-store 模块后，访问网站报错

### ISSUE THREAD

**Issue by tobemaster56** [sub-store-org/Sub-Store#205]
访问 https://sub-store.vercel.app/ 报错

<img width="272" alt="image" src="https://user-images.githubusercontent.com/8998761/232582664-42698f24-381c-4cd9-8905-60a613691329.png">

<img width="432" alt="image" src="https://user-images.githubusercontent.com/8998761/232582101-5d535f8e-910c-41eb-a9ab-b3eeaa76e0d0.png">

**Comment by kieranay** [comment]
我也是同样的问题，请问您后来解决了吗

**Comment by chameloen** [comment]
打开mimt

**Comment by zthxxx** [comment]
@tobemaster56 @kieranay 需要同时开启 Surge 的 `MitM` 和 脚本 `Script` 两个，功能，检查下你们是不是漏了一个
