### ISSUE TITLE
导入订阅，QX节点信息obfs识别错误

### ISSUE THREAD

**Issue by Toperlock** [sub-store-org/Sub-Store#206]
我用机场的订阅导入到sub转换，"obfs=wss"，导致在qx上用不了。但是loon里面传输协议是“transport=ws”能在loon上正常使用。
于是我尝试复制单条节点信息到sub，“obfs=ws”能在qx上正常使用节点。
![sub](https://user-images.githubusercontent.com/86833913/233766975-c7c15494-4bf1-45f4-b2f4-22ebdec4ce89.jpg)

**Comment by xream** [comment]
2.14.16 应该修复了
