### ISSUE TITLE
有支持安卓的客户端吗？

### ISSUE THREAD

**Issue by thexxxroy** [sub-store-org/Sub-Store#207]

**Comment by BaronChushao** [comment]
同问

**Comment by BaronChushao** [comment]
> 用termux

不会用啊

**Comment by xream** [comment]
如果问的是输出支持, 有. 如果问的是在客户端上跑 Sub-Store 服务, 参考: https://xream.notion.site/Sub-Store-Android-0360be9aafb442069951335b02375d74
