### ISSUE TITLE
如何修改节点host或者sni

### ISSUE THREAD

**Issue by lyxhwy** [sub-store-org/Sub-Store#208]
如何修改节点host或者sni
想通过订阅一键修改host混淆,如何修改sni或者host呢

**Comment by lyxhwy** [comment]
@xream @VirgilClyne  求助

**Comment by xream** [comment]
https://github.com/xream/scripts/tree/main/surge/modules/sub-store-scripts/lite

**Comment by lyxhwy** [comment]
> https://github.com/xream/scripts/tree/main/surge/modules/sub-store-scripts/lite

感谢
