### ISSUE TITLE
能否自动添加一个节点，表明最后更新时间以及剩余流量等信息

### ISSUE THREAD

**Issue by ChrisLee0** [sub-store-org/Sub-Store#213]

**Comment by DesnLee** [comment]
这个可能用脚本操作能自己操作上去

**Comment by ChrisLee0** [comment]
> 这个可能用脚本操作能自己操作上去

用脚本添加了当前时间到每个节点

**Comment by xream** [comment]
2.14.82

脚本操作增加流量信息操作 `flowUtils`

流量信息操作用法: 参考 https://t.me/zhetengsha/948

**Comment by 1664167393** [comment]
Lee ***@***.***>于2023年6月25日 周日上午11:16写道：
