### ISSUE TITLE
请求同步当前surge的profile到gist

### ISSUE THREAD

**Issue by ChrisLee0** [sub-store-org/Sub-Store#222]
我不仅多台设备使用surge，还把自己的profile共享给别人。profile同步就成了问题。

surge已经有读取profile的api

GET /v1/profiles/current?sensitive=0

https://manual.nssurge.com/others/http-api.html

我还希望有脚本操作，因为我想在当前profile开头加上 #!MANAGED-CONFIG这样共享给别人就是受管理的profile

**Comment by Peng-YM** [comment]
目前 sub-store 专注于跨软件的订阅管理功能，此类诉求属于 Surge 本身的额外特性，暂时不考虑支持哈
