### ISSUE TITLE
本地订阅转clash不可用

### ISSUE THREAD

**Issue by jaychoubaby** [sub-store-org/Sub-Store#232]
本地订阅值：
`{
type: "ssr",
server: "server",
port: "50568",
protocol: "auth_aes128_md5",
cipher: "aes-256-cfb",
obfs: "obfs",
password: "password",
name: "name",
protocol-param: "37380:kuEqlRD1wN",
obfs-param: "ajax.microsoft.com"
}`

转换后为：
` - {"type":"ssr","server":"server","port":"50568","protocol":"auth_aes128_md5","cipher":"aes-256-cfb","obfs":"tls1.2_ticket_auth","password":"password","name":"name","protocol-param":"37380:kuEqlRD1wN","obfs-param":"ajax.microsoft.com"}`

本地订阅转qx或者小火箭均正常，转clash无法使用，直接ping不通

**Comment by xream** [comment]
使用你的本地订阅值进行转换无法重现转换后的结果 麻烦提供下完整复现流程

**Comment by jaychoubaby** [comment]
> 

隐藏了关键信息，完整配置:
`ssr://aWVwbHN6aGstMDMudGVsZXNjb3Blcy53b3JrOjUwNTY4OmF1dGhfYWVzMTI4X21kNTphZXMtMjU2LWNmYjp0bHMxLjJfdGlja2V0X2F1dGg6YUVkclVUWTVNVFYwUkEvP3JlbWFya3M9OEotSHV2Q2ZoNllnNUxtTTVZV0w1WVd3WDFKZk5UVXgmcHJvdG9wYXJhbT1NemN6T0RBNmEzVkZjV3hTUkRGM1RnJm9iZnNwYXJhbT1ZV3BoZUM1dGFXTnliM052Wm5RdVkyOXQ`

收到请删除节点信息

**Comment by jaychoubaby** [comment]
> 使用你的本地订阅值进行转换无法重现转换后的结果 麻烦提供下完整复现流程

部署方式：docker
clash工具：clash for windows v0.20.31  
clash cord: 2023.07.22 Premiun(64238)
