### ISSUE TITLE
手机端右下角的按钮可能会挡住功能按钮

### ISSUE THREAD

**Issue by himonster1** [sub-store-org/Sub-Store#237]
![image](https://github.com/sub-store-org/Sub-Store/assets/77065609/f56d9928-3f07-4f50-b991-40fa77812c28)

看右下角 刷新和+号按钮，挡住了all-in的右边的按钮

**Comment by xream** [comment]
刷新和+号按钮可以拖动

himonster1 ***@***.***>于2023年9月3日 周日15:02写道：
