### ISSUE TITLE
同步如果有订阅失败就无法同步

### ISSUE THREAD

**Issue by how1ewu** [sub-store-org/Sub-Store#243]
可否设置让用户决定是否跳过失败订阅
我通过发送curl包的方式同步
curl /api/sync/artifacts

**Comment by xream** [comment]
2.14.131

支持忽略失败的远程订阅

前端版本 > 2.14.20 可进行配置

开启后 依赖的远程订阅出错时 不会报错了 需要自行查看日志

组合订阅 与 订阅中的多行订阅 都支持这个开关

同时支持 URL 参数覆盖, 例如: `/download/collection/all?target=Surge&ignoreFailedRemoteSub=true`
