### ISSUE TITLE
[功能请求]对“节点操作”中已键入的正则表达式进行拖动排序

### ISSUE THREAD

**Issue by cc63** [sub-store-org/Sub-Store#244]
希望可以像拖动“节点操作”的模块一样自由的调整已键入信息的顺序。

例如使用“正则排序”功能时，如果后续想微调顺序必须一个一个删掉重新填写；“正则重命名”之类的场景也需要偶尔调整顺序。

请问大佬这个在技术上可以实现吗，如果可以的话请您考虑一下，谢谢☺️

**Comment by cc63** [comment]
我有一些小建议不知道是否合适，请大佬参考一下

因为按钮本身比较小，直接拖动可能不够准确，可以加一个按钮呼出小窗进行排序操作

![image](https://github.com/sub-store-org/Sub-Store/assets/99179360/c5e3e81d-9f7c-41a4-bcd3-ec56596f6793)

然后小窗内将正则表达式逐行排列，类似Surge中对策略组进行排序，这样就可以方便准确的排序了
![image](https://github.com/sub-store-org/Sub-Store/assets/99179360/4797569f-16b3-494a-a3c2-7aea4a497b8c)

**Comment by xream** [comment]
前端[2.14.26](https://github.com/sub-store-org/Sub-Store-Front-End/releases/tag/2.14.26) 做了一个简单的拖拽排序
