### ISSUE TITLE
某些机场订阅GRPC被识别为tcp，同时缺少部分参数

### ISSUE THREAD

**Issue by how1ewu** [sub-store-org/Sub-Store#245]
举例：某机场A存在两个不同订阅连接分别对应v2ray与clash，直接使用机场订阅v2ray连接可获取为：
![image](https://github.com/sub-store-org/Sub-Store/assets/98788152/bc8a971b-68c8-4756-8f9f-0a8db43af02d)
如果使用sub-store订阅v2ray则为：
![image](https://github.com/sub-store-org/Sub-Store/assets/98788152/039ec33e-25e2-4d18-8e5d-43dd0f60f512)
使用substore订阅clash为：
![image](https://github.com/sub-store-org/Sub-Store/assets/98788152/7fa9e50c-0751-415e-9a8a-cc39c9a1ac79)

**Comment by xream** [comment]
精力有限 麻烦提供对应的节点/订阅示例(去掉敏感信息即可)

**Comment by how1ewu** [comment]
> 精力有限 麻烦提供对应的节点/订阅示例(去掉敏感信息即可)

可以留一个邮箱吗，我可以私聊给你订阅信息

**Comment by xream** [comment]
@how1ewu 👌🏻 xreamxu#gmail

**Comment by how1ewu** [comment]
> @how1ewu 👌🏻 xreamxu#gmail
已发送，请查收

**Comment by xream** [comment]
@how1ewu 麻烦测一下 2.14.61 吧

**Comment by how1ewu** [comment]
> @how1ewu 麻烦测一下 2.14.61 吧

感谢，我用的两个类似的机场这个问题都得到了比较好的解决，我认为没有问题了
