### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by jklolixxs** [sub-store-org/Sub-Store#246]
在Safari中，点击分享，添加到主屏幕后，进入主屏幕的Sub-Store，就可以触发这个BUG

复现流程：
设置
关于sub-store
随便点一个  在GitHub上查看
加载好后点左上角完成
退回到sub-store，就会出现（次次都这样）
![photo_2023-10-02_22-39-52](https://github.com/sub-store-org/Sub-Store/assets/69113033/66b6cdf7-a63f-4d3b-9a35-c21df8dc0fee)

**Comment by 1664167393** [comment]
OK

jklolixxs ***@***.***>于2023年10月2日 周一下午10:40写道：
