### ISSUE TITLE
sub-store 同步订阅一直转圈 同步不了怎么处理的

### ISSUE THREAD

**Issue by SaberWu** [sub-store-org/Sub-Store#247]
sub-store 同步订阅一直转圈 同步不了怎么处理的

**Comment by SaberWu** [comment]
[Sub-Store.log](https://github.com/sub-store-org/Sub-Store/files/12836288/Sub-Store.log)
是這个日志吗

**Comment by xream** [comment]
已告知 Stash 开发组

可尝试 https://gist.githubusercontent.com/xream/a4919966ddbc580951d87a2a6f23697b/raw/Sub-Store-1.stoverride

如果不行，尝试

https://gist.githubusercontent.com/xream/a4919966ddbc580951d87a2a6f23697b/raw/Sub-Store-2.stoverride

浏览器里打开 https://sub-store.vercel.app

后端切换为 https://sub2.store 使用

**Comment by SaberWu** [comment]
好的，我测试看看

**Comment by SaberWu** [comment]
可以了，谢谢大佬。
