### ISSUE TITLE
希望能加上sing-box的订阅

### ISSUE THREAD

**Issue by rluoluo** [sub-store-org/Sub-Store#249]

**Comment by FaintGhost** [comment]
附议

**Comment by xream** [comment]
此需求目前仅服务端 Sub-Store 有需求吧. 可选择搭配 https://github.com/Toperlock/sing-box-subscribe https://github.com/xmdhs/clash2sfa

**Comment by xream** [comment]
已支持
生成配置可参考 https://t.me/cool_scripts/487?single
