### ISSUE TITLE
clash.meta转化不出Snell，surge是正常的

### ISSUE THREAD

**Issue by weijingcheng4** [sub-store-org/Sub-Store#256]
Snell=snell,mb.com,443,version=4,psk=Su,shadow-tls-password=Sur,shadow-tls-version=3,shadow-tls-sni=ca.com,reuse=true

**Comment by weijingcheng4** [comment]
好像meta不支持snell🤔

**Comment by xream** [comment]
> 好像meta不支持snell🤔

v4 不支持
