### ISSUE TITLE
跨平台兼容性问题

### ISSUE THREAD

**Issue by augumn** [sub-store-org/Sub-Store#257]
背景：
1.我主要是通过QX 作为sub-store的主机，然后在同步页面上也创建了clash、clash.meta、v2rayN的同步订阅。
2.由于qx支持的协议很少，导致如果使用qx作为主机，在同步页面上clash、clash.meta、v2rayN等工具的订阅也不能出现qx不支持的订阅
3.然而现在大部分的机场都在转向vless+reality，导致同步订阅很少，在其他平台上使用同步订阅时节点也相应变少

**希望改善：**
**同步页面应当是跨平台的，不应受到到当前主机平台的限制。**

**比如：**
**如果通过QX 作为sub-store，那么当创建Loon 的同步订阅时，这时候节点筛选应该是Loon 所有支持的协议，而不是QX支持的协议。**

希望我能把问题描述清楚了，感谢作者的付出让订阅管理变得简单方便。

**Comment by xream** [comment]
> 受到当前主机平台的限制

并没有这个限制

目前默认请求订阅的 `User-Agent` 是 QX 的, 建议先自己改 `User-Agent` 或者使用机场提供的不同客户端的链接 如 `?flag=meta` 等方式.

感谢反馈 怎么改进我们再考虑下(

**Comment by xream** [comment]
忘了说了

版本 2.14.102

支持自定义全局默认 `User-Agent`(后端版本应 > `2.14.101`)

全局默认 `User-Agent` 从 `Quantumult%20X/1.0.29 (iPhone14,5; iOS 15.4.1)` 改成了 `clash.meta`
