### ISSUE TITLE
根据Development指导，运行出错

### ISSUE THREAD

**Issue by YcccByHe** [sub-store-org/Sub-Store#258]
根据Development指导运行后报模块无法找到，实际模块是存在的，能看下是什么原因吗
![image](https://github.com/sub-store-org/Sub-Store/assets/55644381/e792409b-8a64-45c5-8f5b-cb2446d7a37f)

**Comment by xream** [comment]
似乎是 babel-plugin-relative-path-import 插件转换路径时不兼容 Windows. 不推荐使用 Windows 进行开发, 但是欢迎 pr

**Comment by DesnLee** [comment]
试试 PowerShell 7 或者 WSL2 开发

**Comment by YcccByHe** [comment]
> 是欢迎 pr
使用Linux可以吗

**Comment by xream** [comment]
实验性加入了 esbuild 可以尝试一下 `pnpm run --parallel --stream "/^dev:.*/"`
