### ISSUE TITLE
[功能请求] 添加 `config` 参数以支持指定配置模板

### ISSUE THREAD

**Issue by y1ndan** [sub-store-org/Sub-Store#262]
我在使用 Sub-Store 将订阅数据转换为 Clash 格式时，发现目前的输出结果仅有 `proxies` 部分。在原样使用此订阅链接作为 Clash for Windows 的远程配置文件时，只有全局选项下有节点，无法实现分流功能。

能否添加 `config` 参数来指定本地或远程的配置模板，用以定制 `proxy-groups`, `rules` 等模块的内容？

**Comment by Peng-YM** [comment]
sub-store 目前对所有平台的输出都仅包含节点列表，建议 Clash 中使用规整集 + 策略集（sub-store 生成）进行配置

**Comment by y1ndan** [comment]
> Clash 中使用规整集 + 策略集（sub-store 生成）进行配置

是说要新建一个本地.yaml然后指定 `proxy-providers` 为生成链接吗？能否展开说说，谢谢。

**Comment by xream** [comment]
> > Clash 中使用规整集 + 策略集（sub-store 生成）进行配置
> 
> 是说要新建一个本地.yaml然后指定 `proxy-providers` 为生成链接吗？能否展开说说，谢谢。

比如你可以 Gist 上建一个 yaml 配置, `proxy-providers` 里使用 Sub-Store `?target=Clash` 的订阅链接 `proxy-groups` 再使用它. 都是能搜索到的内容, 没必要在本项目 issue 里展开了.

**Comment by y1ndan** [comment]
明白，谢谢三位的解答。
