### ISSUE TITLE
为啥socks5://192.168.177.110:10808填入后无效呢？

### ISSUE THREAD

**Issue by MalikWilliams1greher** [sub-store-org/Sub-Store#264]
<img width="439" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/147643826/dc8aed59-eb59-4104-965d-121e8561fd0c">
即时预览 里面 一片空白

**Comment by MalikWilliams1greher** [comment]
<img width="333" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/147643826/9431954c-d9e6-4101-bdb8-1288270704c6">

**Comment by MalikWilliams1greher** [comment]
直接订阅本地链接 然后用SOCKS5链接，语法错误吗？为啥不出来节点呢

**Comment by xream** [comment]
1. URI 输入时, 目前支持 SS SSR VMess VLESS Hysteria2 Trojan, 没有 SOCKS5
2. 可以用 Surge 等代理的格式 例如 `test = socks5, 127.0.0.1, 1080`
3. 如无必要 请勿刷多条 comment

**Comment by MalikWilliams1greher** [comment]
好的 谢谢

`test = socks5, 127.0.0.1, 1080` 是写在Surge的配置文件里面吗

**Comment by xream** [comment]
<img width="433" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/c1fc64c7-e21b-488e-87d2-7ce44a357633">

**Comment by MalikWilliams1greher** [comment]
好的 非常感谢，请问使用Sub-Store可以让Surge使用vless节点吗

**Comment by xream** [comment]
你在问什么...Surge 本体不支持 就算输出了有什么用

**Comment by MalikWilliams1greher** [comment]
明白了 谢谢大佬 我还希望能有黑科技呢 😄


----

另外还想请问一下，为啥README.md里面写支持SOCKS5，但是实际上又不能直接输入SOCKS5链接来订阅呢（没有其他意思，纯好奇，不想回答可以不回这条，我的问题已经完美解决了，谢谢大佬）

```
Surge (SS, VMess, Trojan, HTTP, SOCKS5, TUIC, Snell, Hysteria2, SSR(external, only for macOS), WireGuard(Surge to Surge))
```

https://github.com/sub-store-org/Sub-Store#supported-input-formats

**Comment by xream** [comment]
没写 SOCKS5 URI
你引用的部分恰恰就是写的 Surge 格式的 SOCKS5
