### ISSUE TITLE
surge 订阅里的 trojan 会被错误的解析成ssr

### ISSUE THREAD

**Issue by vangie** [sub-store-org/Sub-Store#265]
订阅格式如下

```
[Pro]VN-越南-1-2倍 = trojan, xxxx, 1616, password=xxx, sni=xxx, udp-relay=true, skip-cert-verify=true, tfo=true, hybrid=true
[Pro]EG-埃及-1-2倍 = trojan, xxx, 1576, password=xxx, sni=xxx, udp-relay=true, skip-cert-verify=true, tfo=true, hybrid=true
```

解析出来的格式如下
```
{
"name": "🇪🇬 EG-埃及-1-2倍",
"type": "ssr",
"server": "xxx",
"port": 1571,
"cipher": "chacha20-ietf",
"password": "xxx",
"udp": true,
"protocol": "auth_aes128_md5",
"protocol-param": "126057:hwYRqh",
"obfs": "plain",
"obfs-param": "xxx",
"flags": null,
"subName": "fatty"
}
```

**Comment by xream** [comment]
你提供的这两行本地订阅肯定不会变成后面你贴的结果...

**Comment by vangie** [comment]
我新建了一个订阅，同样的url订阅，还是上面的结果，非常奇怪，会不会有缓存文件之类的。

**Comment by xream** [comment]
首页右下角悬浮的刷新按钮清一下缓存看看

Vangie Du ***@***.***>于2023年12月30日 周六22:56写道：

**Comment by vangie** [comment]
我清理过了，没有解决。本地缓存的路径在什么位置，是可读的文本文件么？

**Comment by xream** [comment]
Node.js 版是 root.json, App 版里持久化缓存 key 为 sub-store-cached-resource

**Comment by vangie** [comment]
<img width="1378" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1388582/f1e9edbb-aabd-46b2-8c8f-5a8de845837c">
<img width="1378" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1388582/6b1fbfba-85ab-40a2-887e-825ae928c3d3">

你看，还是有相关性的。

**Comment by xream** [comment]
不会无中生有. 我猜你其实不是用的本地订阅, 而是用的 远程订阅链接.
而 Sub-Store 默认的 User-Agent 是 Clash.Meta. 所以下发了 SSR 节点(图2).
图1是下发的 Surge 配置(Surge 不支持 SSR 所以下发了 Trojan)

**Comment by vangie** [comment]
这是我另外一个ssr的订阅，

![image](https://github.com/sub-store-org/Sub-Store/assets/1388582/787da6f4-40df-4aa4-a030-795f3bec0031)

我觉得两个订阅存在数据冲突了

**Comment by vangie** [comment]
![image](https://github.com/sub-store-org/Sub-Store/assets/1388582/7d91db45-cb2d-49d0-831e-dc8782efae85)

**Comment by xream** [comment]
没看出你得出这个结论的依据是什么. 我上条回复猜测的情况不对吗? 你可以用不同的 User-Agent 进行验证. 很容易就能分辨. 你给 Super small and fat 把订阅的 User-Agent 设为 Surge 尝试下.

**Comment by vangie** [comment]
我之前配置好了的，大概前端时间升级过一次后出问题了。

**Comment by xream** [comment]
嗯 默认 User-Agent 换过. 之前默认是 QX 的

**Comment by vangie** [comment]
![image](https://github.com/sub-store-org/Sub-Store/assets/1388582/fa7dedd2-8337-46d8-997a-ac52d14767e3)
这里默认有查询参数，所以需要指定User-Agent么？我直接访问上面的订阅链接，返回的就是surge的配置。

**Comment by xream** [comment]
得看机场后端. 有的后端 User-Agent 优先. 你设置下 User-Agent 尝试下. 如果还是无法解决, 可以私发我订阅. 我调试完你重置订阅即可.

**Comment by vangie** [comment]
> 得看机场后端. 有的后端 User-Agent 优先. 你设置下 User-Agent 尝试下. 如果还是无法解决, 可以私发我订阅. 我调试完你重置订阅即可.

真的是这个问题，User-Agent 设置成 Surge 就好了。当前 User-Agent 的默认值是什么？

**Comment by xream** [comment]
@vangie clash.meta

**Comment by vangie** [comment]
非常感谢！

为了让Surge里可以跑SSR订阅，我写了一个额外的 Surge module 来做转换，如果 Sub.store 能支持的话，就好了。https://github.com/vangie/ssr-surge

**Comment by xream** [comment]
@vangie 有做这个：
根据 User-Agent 识别 macOS 版 Surge(也可指定参数 target=SurgeMac) 并支持 SSR 协议(节点字段 exec 为 ssr-local 路径, 默认 /usr/local/bin/ssr-local; 端口从 10000 开始递增, 暂不支持配置)

**Comment by vangie** [comment]
太棒了，exec  /usr/local/bin/ssr-local，在哪里可以改么？

**Comment by xream** [comment]
<img width="474" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/f4377460-97ee-4d1f-9389-801f1f886822">

现在的做法是如图设置

**Comment by vangie** [comment]
好用，我的问题被完美解决了，赞👍🏻
