### ISSUE TITLE
Quantumult X does not work after using readme configuration

### ISSUE THREAD

**Issue by Amazon90** [sub-store-org/Sub-Store#266]
https://github.com/sub-store-org/Sub-Store/blob/master/config/README.md

![image](https://github.com/sub-store-org/Sub-Store/assets/72290820/a639dcae-4e24-4e13-b38a-f2d3f25d89b6)

![image](https://github.com/sub-store-org/Sub-Store/assets/72290820/0d55f8c1-87be-4fff-8a39-f358209a77e8)

![image](https://github.com/sub-store-org/Sub-Store/assets/72290820/65d951b4-950a-4ec4-a4be-6efb0119b2ff)

**Comment by xream** [comment]
Generally speaking, you need to use a proxy to access https://sub-store.vercel.app.

**Comment by Amazon90** [comment]
> Generally speaking, you need to use a proxy to access https://sub-store.vercel.app.

Thank you. I found the cause of the issue. Vercel.com is no longer accessible in Hong Kong.
