### ISSUE TITLE
请问圈x教程里面的 定时脚本 怎么用？没找到在哪添加

### ISSUE THREAD

**Issue by MalikWilliams1greher** [sub-store-org/Sub-Store#267]
https://github.com/sub-store-org/Sub-Store/tree/master/config#:~:text=https%3A//raw.githubusercontent.com/sub%2Dstore%2Dorg/Sub%2DStore/master/config/QX%2DTask.json

<img width="958" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/147643826/5c0f1737-f099-49aa-91b2-37239d8555a1">

**Comment by xream** [comment]
代理 App 如何使用请自行解决. 请勿在本项目提交无关 issue.
