### ISSUE TITLE
节点手动编辑

### ISSUE THREAD

**Issue by wuguipeng** [sub-store-org/Sub-Store#268]
通过base64导入进来的节点，可以进行手动编辑吗？

节点套用中转机的时候，需要把ip，端口替换，不支持手动编辑的话base64转来转去比较麻烦。

**Comment by xream** [comment]
@wuguipeng 不管你用什么方式导入 都是支持的 参考 https://t.me/cool_scripts/451

**Comment by wuguipeng** [comment]
> @wuguipeng 不管你用什么方式导入 都是支持的 参考 https://t.me/cool_scripts/451

好的谢谢
