### ISSUE TITLE
client-fingerprint missing to tls-fingerprint?

### ISSUE THREAD

**Issue by Ariesly** [sub-store-org/Sub-Store#272]
all ```client-fingerprint``` change to ```tls-fingerprint```?

[/backend/src/core/proxy-utils/producers/uri.js#L146](https://github.com/sub-store-org/Sub-Store/blob/master/backend/src/core/proxy-utils/producers/uri.js#L146)
[/backend/src/core/proxy-utils/producers/sing-box.js#L203](https://github.com/sub-store-org/Sub-Store/blob/master/backend/src/core/proxy-utils/producers/sing-box.js#L203)
[/backend/src/core/proxy-utils/parsers/index.js#L395](https://github.com/sub-store-org/Sub-Store/blob/master/backend/src/core/proxy-utils/parsers/index.js#L395)

e.g. 
```
hysteria2://letmein@example.com/?insecure=1&obfs=salamander&obfs-password=gawrgura&pinSHA256=deadbeef&sni=real.example.com
```

output: missing fingerprint info

```
[
  {
    "tag": "Hysteria2 example.com:443",
    "type": "hysteria2",
    "server": "example.com",
    "server_port": 443,
    "password": "letmein",
    "obfs": {
      "type": "salamander",
      "password": "gawrgura"
    },
    "tls": {
      "enabled": true,
      "server_name": "real.example.com",
      "insecure": true
    }
  }
]
```

**Comment by xream** [comment]
@Ariesly Is this correct? 4240453

**Comment by xream** [comment]
Sorry, fingerprint and client-fingerprint are not the same thing. I'll check it later.

**Comment by Ariesly** [comment]
if not the same thing, meybe need change to ```client-fingerprint```
[/backend/src/core/proxy-utils/parsers/index.js#L502](https://github.com/sub-store-org/Sub-Store/blob/master/backend/src/core/proxy-utils/parsers/index.js#L502)

and other related ones also need to change accordingly. 

e.g.

[/backend/src/core/proxy-utils/producers/uri.js#L266](https://github.com/sub-store-org/Sub-Store/blob/master/backend/src/core/proxy-utils/producers/uri.js#L266)

**Comment by xream** [comment]
@Ariesly `client-fingerprint` is ClientHello fingerprint.

`fingerprint` is a pinned server certificate.

It seems that sing-box does not have this feature.

**Comment by Ariesly** [comment]
sing-box TLS
Changes in sing-box 1.8.0

[https://sing-box.sagernet.org/configuration/shared/tls/#utls](https://sing-box.sagernet.org/configuration/shared/tls/#utls)

new feature in 1.8.0?

**Comment by Ariesly** [comment]
oh, utls ```fingerprint``` is Chrome client fingerprint
not the cert fingerprint.
