### ISSUE TITLE
[功能建议] 复制粘贴现有的“操作”

### ISSUE THREAD

**Issue by cc63** [sub-store-org/Sub-Store#278]
有些对节点的操作适用于很多订阅，例如“正则重命名”“正则排序”，如果每个订阅都重新输入一遍会很麻烦。

能否在已经编辑好的操作上加一个“复制”按钮，然后在“添加一个操作”的位置加一个“粘贴操作”

![image](https://github.com/sub-store-org/Sub-Store/assets/99179360/ffa760a0-948b-45d3-bdac-f4e812e489c0)

![image](https://github.com/sub-store-org/Sub-Store/assets/99179360/92eb5244-92bf-4591-8fed-088b35f364c7)

这样就很方便，适合不懂脚本的用户（我

**Comment by xream** [comment]
备忘: 前端 2.14.132 支持了此功能
