### ISSUE TITLE
到底咋用？云vscode环境 pnpm start 一直提示找不到 后端？？？不是启动在:::3000端口了?

### ISSUE THREAD

**Issue by gowy222** [sub-store-org/Sub-Store#279]
如题..

**Comment by xream** [comment]
1. 开发

参考文档中的开发部分

![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/6411875c-33a3-4b45-9383-322be15f5db6)


2. 仅使用

直接用 releases 里的 `sub-store.bundle.js` 就行

或者查看 https://xream.notion.site/Sub-Store-abe6a96944724dc6a36833d5c9ab7c87
