### ISSUE TITLE
将常用参数添加到常用配置里

### ISSUE THREAD

**Issue by jockstrap1044** [sub-store-org/Sub-Store#280]
可以将 noFlow noCache validCheck 这几个参数直接添加到这里面吗？
![image](https://github.com/sub-store-org/Sub-Store/assets/132739204/8acd3e5d-7a7a-4533-b815-ac7f5b5418f9)

或者添加到这下面，增加一个选项
![image](https://github.com/sub-store-org/Sub-Store/assets/132739204/84aaa6b9-3dce-4985-8049-172723718849)

这样就不用每次都写了

**Comment by xream** [comment]
可能以后会改, 但是不会如你建议的方式改. 因为订阅链接那个输入框里可以换行填多个订阅, 而参数是跟在每一个订阅链接上的.

**Comment by jockstrap1044** [comment]
> 可能以后会改, 但是不会如你建议的方式改. 因为订阅链接那个输入框里可以换行填多个订阅, 而参数是跟在每一个订阅链接上的.

好的，感谢大佬
