### ISSUE TITLE
[Bug] 在特定情景下，无法在订阅的「脚本操作」中执行存储在「文件管理」中的脚本

### ISSUE THREAD

**Issue by jimlee2048** [sub-store-org/Sub-Store#281]
## 环境
使用Docker部署的服务器版sub-store，https://hub.docker.com/r/xream/sub-store

## 问题描述
如果满足以下条件，那么无法在订阅的「脚本操作」中执行存储在「文件管理」中的脚本：
- 「文件管理」中添加的脚本，来源为「仅远程」或「远程优先」
- 在订阅的「脚本操作」中，以`/api/file/***`形式的内部短链接引用脚本

## 错误日志
```log
[sub-store] INFO: Applying "Script Operator" with arguments:
 >>> {
  "content": "/api/file/sub-info-node.js",
  "mode": "link"
}
[sub-store] ERROR: Cannot apply operator Script Operator(function operator)! Reason: ReferenceError: operator is not defined
```

## 复现情景

1. 在文件管理中，仅添加远程脚本链接
![SCR-20240213-tlvh](https://github.com/sub-store-org/Sub-Store/assets/21117946/ebf12318-4f33-4792-8594-6a1e90c2219d)
```
https://cdn.jsdelivr.net/gh/xream/scripts@main/surge/modules/sub-store-scripts/sub-info/node.js
```
保存后复制链接，在提示中得到文件管理中的内部短链接
```
/api/file/sub-info-node.js
```

2. 编辑任一订阅，添加脚本操作，填写刚才所得短链接。此时点击预览，脚本不工作（没有出现流量信息节点），后端出现上文错误日志。
![SCR-20240213-tnii](https://github.com/sub-store-org/Sub-Store/assets/21117946/58236ca2-68f6-4956-b99a-f0ecd8c3a8c1)

3. 填写文件管理中复制所得的完整链接（带域名）或直接填写脚本源链接，脚本均能正常工作（能正常出现流量信息节点）

**Comment by xream** [comment]
没注意到这里...目前仅支持本地文件内容的复用. 服务器版要复用的话, 直接在脚本操作里填文件的完整链接吧

**Comment by xream** [comment]
@jimlee2048 2.14.219 已支持
