### ISSUE TITLE
在Apple TV（Surge）中配置Sub-Store

### ISSUE THREAD

**Issue by lukedumboy** [sub-store-org/Sub-Store#283]
在使用apple tv配置sub-store时，我做了以下步骤
1，在iOS端的surge导出了证书，然后让appletv下载并信任
2，使用其他设备设置apple tv为网关，由此访问apple tv内的sub store
3，根据配置教程配置完成后，网页端可以进入，也可以正常数据刷新，节点都可以看得到
4，出现问题了，在把订阅信息填入配置文件进行同步的时候只要一更新，就会出现以下字样

DNS lookup failed: Empty DNS response for sub.store from all DNS servers: 223.5.5.5, 114.114.114.114 (SGErrorDomain:1)

同样的dns在iOS上可以正常更新使用
因为没有任何节点，所以默认使用的是直连，节点信息是通过其他配置文件更新完成之后才切换回来的

**Comment by xream** [comment]
我没有 Apple TV, 无法测试. 
能使用 TV 端的网页版 意味着 sub.store 的重写肯定已经生效了, 应该不会有别的问题.
可以尝试在 https://t.me/SURGEPRO 寻求帮助, 并更新此 issue

**Comment by LiangTian418** [comment]
经过各位大佬指导调试最后sub-store部署正常，除Atv自身拉取不了订阅其他设备均能拉取订阅，关于ATV拉取不了是tv端本身不支持，已破案
![IMG_9292](https://github.com/sub-store-org/Sub-Store/assets/79867425/d92f3a43-56cc-4790-9091-440971b12f69)

**Comment by LiangTian418** [comment]
经过各位大佬指导调试最后sub-store部署正常，除Atv自身拉取不了订阅其他设备均能拉取订阅，关于ATV拉取不了是tv端本身不支持，已破案
![IMG_9293](https://github.com/sub-store-org/Sub-Store/assets/79867425/1c5de26f-ca93-42ce-bf2f-73c3017eaca1)

**Comment by Jarynq** [comment]
请问iPhone如何访问tvos的substore

**Comment by lukedumboy** [comment]
> 请问iPhone如何访问tvos的substore

请按照第2步操作

**Comment by Jarynq** [comment]
把apple tv设置成手机网关直接访问sub.store么
