### ISSUE TITLE
关于刷新的优化

### ISSUE THREAD

**Issue by jockstrap1044** [sub-store-org/Sub-Store#285]
大佬，现在左上角的刷新按钮或者设置的悬浮刷新按钮点击后还是有很多显示加载中

并且反复点击刷新按钮等待很久还是显示加载中，必须单独点击对应条目的刷新才能加载出来

经过测试发现是有一条订阅挂了，导致始终在请求那一条，从而使那条订阅之后的所有订阅都刷新不出来，必须手动点击对应的才行

能优化一下刷新逻辑吗？遇到这种链接挂了的，设置一个超时之类的，超过一定时间没刷新出来就跳过？

**Comment by xream** [comment]
无法重现. 我只能重现这样的情况: 
因为获取流量信息的请求是分批次的, 如果有一批次中的某一条超时了, 看上去就是有多条一直在加载中.
等这一批次(超时)完成之后, 这一批次的订阅才会显示完成.

而超时功能早就做了. 你设置一个合理的时间就可以更快结束.

PS: 刷新按钮其实不是刷新...是更新头像等数据并清空缓存.

订阅信息是前端的. 其实你刷新前端就可以了.

**Comment by jockstrap1044** [comment]
现在情况是这样的
---
订阅1

订阅2

订阅3

订阅4

订阅5
---
订阅1，2都可以获取，订阅3出了问题，导致订阅3,4,5都一直显示加载中。直接点击订阅4,5的刷新是可以刷新出来的，使用左上角的刷新和悬浮刷新都不行，这几个刷新功能不一样吗？

订阅链接是这个 https://www.yunqiezi.top/link/Sh6foV4bdjEJn5TQ?clash=1#noCache&validCheck

这个链接之后的所有订阅都显示加载中，等了十几分钟还是显示加载中，直接刷新前端F5吗？刷新完之后还是一样的结果

**Comment by xream** [comment]
上面已经解释过了. 你的这个我仍然无法重现.

> 而超时功能早就做了. 你设置一个合理的时间就可以更快结束.

请设置超时后尝试

**Comment by jockstrap1044** [comment]
> 上面已经解释过了. 你的这个我仍然无法重现.
> 
> > 而超时功能早就做了. 你设置一个合理的时间就可以更快结束.
> 
> 请设置超时后尝试

😂好的，麻烦大佬喂饭了，一直没设置那个超时
