### ISSUE TITLE
TUIC-v5 服务器证书指纹丢失

### ISSUE THREAD

**Issue by Skyxim** [sub-store-org/Sub-Store#287]
环境: 
Node - 2.14.225

1. surge 格式配置，输入本地订阅
```
test = tuic-v5, test.com, 443, password=123, sni=osxapps.itunes.apple.com,uuid=25222C3C-5439-475E-B48F-CB31EA511694, alpn=h3,server-cert-fingerprint-sha256=a5:11:8c:51:da:98:ff:b3:17:83:f0:0b:09:1f:7e:a3:42:e5:2b:90:f9:b1:10:27:3d:3b:3d:90:33:ac:3e:2d
```
![image](https://github.com/sub-store-org/Sub-Store/assets/70276018/82d9b9a2-d11b-4023-89db-2fd894e32ba3)

2. 订阅输出不存在指纹
查看 Surge，Clash.Meta 皆丢失
![image](https://github.com/sub-store-org/Sub-Store/assets/70276018/873b784f-92d9-476c-877b-ceb99ec67178)

**Comment by xream** [comment]
TUIC 的都漏了...过会儿试试 2.14.227
