### ISSUE TITLE
可以在订阅链接中隐藏后端地址吗

### ISSUE THREAD

**Issue by UntaggedRui** [sub-store-org/Sub-Store#288]
感谢开发sub-store这么好用的工具。目前使用的是docker版本的xream/sub-store，搭建在自己的vps上。
有个问题是如果将订阅地址分享给别人的话，而订阅连接中包含着后端地址，其他人可以通过访问前端填入后端地址查看我的sub-store中的所有内容。
所以如何能在订阅链接中隐藏后端地址，使得别人无法通过订阅链接拿到前端后端地址从而获得该sub-store中的所有内容呢？

**Comment by xream** [comment]
反代中进行配置
或分享 gist 链接给他们
