### ISSUE TITLE
可以在组合订阅中增加 surge underlying-proxy 的配置吗？

### ISSUE THREAD

**Issue by q118118** [sub-store-org/Sub-Store#291]
这配置可以让这些代理可以作为 Proxy chain 的出口，谢谢。

**Comment by xream** [comment]
![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/f1d5041d-48ac-47fb-986c-c5d37a1f1dbd)
`$server['underlying-proxy'] = "xxxxx"`

**Comment by q118118** [comment]
感谢🙏
