### ISSUE TITLE
请问大佬怎么定时更新机场订阅

### ISSUE THREAD

**Issue by MalikWilliams1greher** [sub-store-org/Sub-Store#292]
比如 60分钟更新一次机场订阅

**Comment by xream** [comment]
1. 拉取 Sub-Store 订阅时, 会自动拉取远程订阅
2. 远程订阅缓存是 1 小时, 缓存的唯一 key 为 url+ user agent. 可通过前端的刷新按钮刷新缓存. 或使用参数 `noCache` 来禁用缓存. 例: `http://a.com#noCache`

如果你能理解, 那么我觉得你应该重新换个方式提问. 谢谢
