### ISSUE TITLE
能不能支持过滤掉无法ping通的节点

### ISSUE THREAD

**Issue by cikichen** [sub-store-org/Sub-Store#293]
从网上找的免费节点可能有几百个，但是能用的一般就几个，能否直接过滤掉无法ping通的节点？

**Comment by xream** [comment]
参考 Key 佬的 https://github.com/Keywos/rule/blob/main/pname.js

**Comment by cikichen** [comment]
> 参考 Key 佬的 https://github.com/Keywos/rule/blob/main/pname.js

docker版本直接报错了
<img width="310" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1478821/b2bcbc9e-7dd5-4cb3-9936-1323953ffcd1">

**Comment by cikichen** [comment]
> 参考 Key 佬的 https://github.com/Keywos/rule/blob/main/pname.js

docker版本貌似不行，全是超时
2024-03-11T08:24:53.035474068Z [PNAME] [VMess] 🇺🇸 美国 CloudFlare节点 34-> [OUTKApi超时查询次数] 1
2024-03-11T08:24:53.039032176Z [PNAME] Target platform: true is not supported!
2024-03-11T08:24:53.039469960Z [PNAME] 单条订阅脚本免费每小时更新 处理完后剩余: 0 个
2024-03-11T08:24:53.040370992Z [PNAME] 单条订阅脚本免费每小时更新 此方法总用时: 2秒

**Comment by xream** [comment]
等我写一个新的

**Comment by cikichen** [comment]
> 等我写一个新的

<img width="602" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1478821/eb6de194-1ee2-44da-81b3-6a76f7eeaa0e">
不大准

**Comment by cikichen** [comment]
<img width="650" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1478821/c96bc0da-48bc-4016-953b-9797b432d5c9">

**Comment by xream** [comment]
@cikichen 请勿进行无效反馈 可使用 https://t.me/zhetengsha/1210 并进群交流
