### ISSUE TITLE
为什么我部署老是提醒我无效api，后端ip+端口或者域名都进不去，前端正常

### ISSUE THREAD

**Issue by im-dashan** [sub-store-org/Sub-Store#296]
为什么我部署老是提醒我无效api，后端ip+端口或者域名都进不去，前端正常

**Comment by xream** [comment]
请勿在此做这种无效反馈

1. 相关教程很多 可以参考 https://xream.notion.site/Sub-Store-Docker-8efc1aea40fa431b9a562b78994e7fb8

2. 有可能是因为你防火墙端口没开 或 你默认监听的是 `127.0.0.1`
