### ISSUE TITLE
订阅分组功能

### ISSUE THREAD

**Issue by armful5862** [sub-store-org/Sub-Store#297]
订阅过多，导致有点混乱，可以弄个分组显示吗？比如支持将123订阅分到一个组，然后支持折叠显示，组合订阅里支持直接选分组。
更加方便排序，比如一些快到期的，可以放到一个组里，还可以直接添加订阅到当前分组里，不用再从最后一个拖到最上面这种情况。失效了直接删除整个组，组合订阅里也不用点多次，直接一个分组搞定。

仅做一个参考思路，给大佬递茶🍵

**Comment by xream** [comment]
前端 2.14.170

订阅支持支持标签分组

支持收起/展开订阅

至于组合订阅中使用分组 我还得再想想...

**Comment by armful5862** [comment]
> 前端 2.14.171
> 
> 订阅支持标签分组
> 
> 组合订阅中的子订阅支持分组筛选(仅支持筛选, 未实现动态绑定一个分组的所有订阅)
> 
> 支持收起/展开订阅
> 
> 至于组合订阅中使用分组 我还得再想想...

使用了一下，提供一个优化思路，在更多设置或主页右上角提供一个开关，来快速筛选未整理（没有标签或分组），类似于一些相册软件中仅看未整理的图片这样的功能。

**Comment by armful5862** [comment]
> 2.14.175 加了未分组(若存在未分组的项时才会显示)

建议支持隐藏【全部】标签页，可以在更多设置里放个开关，默认不打开，有需要的可以打开

**Comment by xream** [comment]
好像没必要. 如果没有加过标签, 就不会有分组. 而有分组的时候, 进去订阅页, 默认就是全部也很合理吧. 去掉的话, 默认是在第一个分组上? 有点奇怪

**Comment by armful5862** [comment]
> 好像没必要. 如果没有加过标签, 就不会有分组. 而有分组的时候, 进去订阅页, 默认就是全部也很合理吧. 去掉的话, 默认是在第一个分组上? 有点奇怪

那先不考虑这个，能否支持在组合订阅里的分组全选？这样就可以批量取消和选择了

**Comment by armful5862** [comment]
还有分组的时候，能否读取已有标签，直接进行选择，而不是反复输入？

**Comment by xream** [comment]
> > 好像没必要. 如果没有加过标签, 就不会有分组. 而有分组的时候, 进去订阅页, 默认就是全部也很合理吧. 去掉的话, 默认是在第一个分组上? 有点奇怪
> 
> 那先不考虑这个，能否支持在组合订阅里的分组全选？这样就可以批量取消和选择了

这个应该会加

**Comment by xream** [comment]
> 还有分组的时候，能否读取已有标签，直接进行选择，而不是反复输入？

这个得看看. 其实我做了一版, 但是新的组件跟现在的组件各方面都不搭, 改起来有点费劲...

**Comment by xream** [comment]
> > 好像没必要. 如果没有加过标签, 就不会有分组. 而有分组的时候, 进去订阅页, 默认就是全部也很合理吧. 去掉的话, 默认是在第一个分组上? 有点奇怪
> 
> 那先不考虑这个，能否支持在组合订阅里的分组全选？这样就可以批量取消和选择了

2.14.208 已实现

**Comment by armful5862** [comment]
希望支持添加订阅按当前分组顺序自动排序

比如说我现在有全部【A、B、C】，长期【A】，限时【B】，白嫖【C】，这几个分组

现在我在长期里新增一条【D】当前长期【A、D】

那么在全部里默认会添加到最后，当前全部【A、B、C、D】

而我希望他能按照分组顺序长期——限时——白嫖，这样的顺序自动排序

也就是全部【A、D、B、C】

仅供参考，大佬辛苦

**Comment by xream** [comment]
刚刚尝试实现了一下 感觉怎么弄都有点怪...因为可能有 A, A, B, A 这种情况...
其实手动也不麻烦吧

**Comment by xream** [comment]
后端 2.14.394 前端 2.14.271 组合订阅支持通过单条订阅的标签进行关联
