### ISSUE TITLE
[BUG] 流量情况获取超时，订阅会直接消失

### ISSUE THREAD

**Issue by cc63** [sub-store-org/Sub-Store#299]
如果订阅链接加载非常慢，被判断为超时后，该条订阅会直接消失，刷新页面会重新出现并再次开始加载。（以前超时会显示“刷新后可获取流量情况”）

仅在“获取流量情况超时”时会触发这个问题，“不查询/订阅链接错误”都没问题

**Comment by cc63** [comment]
https://github.com/sub-store-org/Sub-Store/assets/99179360/b9569976-bd2b-4c9c-934c-b1219e25e8b2

**Comment by xream** [comment]
😱 我无法复现 不知道为啥 如果你能提供前端日志就好了 我怀疑是有什么异常数据 前端寄了

**Comment by cc63** [comment]
![IMG_4911](https://github.com/sub-store-org/Sub-Store/assets/99179360/9193c958-d31c-4e52-8a46-7d572ce5b287)
🥹是这个吗，就是超时才会触发，现在不超时了就一切正常

**Comment by xream** [comment]
<img width="701" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/76f9198f-d4d7-4bfe-a2e9-bc10d34b27c2">
你在设置里加上超时试试

**Comment by cc63** [comment]
设置了4000，订阅链接超时的时候还是可以复现😢

**Comment by cc63** [comment]
只是在首页不显示了，组合订阅和gist同步里面依然可以看到

**Comment by cc63** [comment]
前端：v2.14.201 已修复
