### ISSUE TITLE
如何在脚本运算符中获取文件内容

### ISSUE THREAD

**Issue by kien8995** [sub-store-org/Sub-Store#300]
我想在很多地方重用文件的内容。 如何通过脚本运算符中的脚本获取文件内容
或类似的东西 `$.http.get('/api/file/sni')`

![Screenshot 2024-03-20 at 5 05 23 PM](https://github.com/sub-store-org/Sub-Store/assets/10568426/3bf88e90-c321-4a3d-afd5-2d3230f7801c)

**Comment by xream** [comment]
@kien8995 参考
<img width="468" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/df6041c3-c2f8-4cf5-8271-4528f7b7780a">
```
const sni = await produceArtifact({
    type: 'file',
    name: 'sni' // 文件名
});

$server.sni = sni
```
