### ISSUE TITLE
脚本使用问题

### ISSUE THREAD

**Issue by jockstrap1044** [sub-store-org/Sub-Store#301]
大佬，我想问一下
----------情景1
订阅1——使用了节点测活和GPT 检测
订阅2——使用了节点测活和GPT 检测
订阅3——使用了节点测活和GPT 检测

组合订阅A：订阅1，订阅2，订阅3
-----------情景2
订阅1
订阅2
订阅3

组合订阅B：订阅1，订阅2，订阅3——使用了节点测活和GPT 检测

第一种情况中我在几个订阅里都添加了节点测活和GPT 检测脚本，之后组成订阅A
第二种情况是我在几个订阅里不使用脚本，而是组合得到订阅B，后再使用节点测活和GPT 检测脚本

哪种更好一些？更推荐分别处理之后组合还是先组合再处理？

还有我发现使用脚本时，比如第一种情况中的订阅1，我手动点击预览是可以看到里面是有可用节点的，但经常组合后得到的订阅A里就没有了，是因为节点过多导致的吗？

**Comment by xream** [comment]
1. 看情况
2. 可能是吧 具体得看为啥失败了. 之前写的没加缓存, 我加个缓存可能会好一些.

**Comment by jockstrap1044** [comment]
> 1. 看情况
> 2. 可能是吧 具体得看为啥失败了. 之前写的没加缓存, 我加个缓存可能会好一些.

不清楚，单独点预览的话每次都是有存活节点的，但组合后就很容易丢失
