### ISSUE TITLE
如何只加载一个订阅

### ISSUE THREAD

**Issue by kien8995** [sub-store-org/Sub-Store#302]
我有两个远程订阅，一个用于使用（`sub A`），一个用于备份（`sub B`）。 然后我将它们合并为一个集合（`collection C`）。 如何仅从其中之一（`sub A` 或 `sub B`）获取代理，当（`sub A`）无法从服务器获取代理时仅从（`sub b`）获取代理。 我如何在 javascript 脚本中做到这一点。

![Screenshot 2024-03-22 at 4 38 19 PM](https://github.com/sub-store-org/Sub-Store/assets/10568426/6bc10992-81ce-4aa5-8aca-1ad535825475)

**Comment by xream** [comment]
1. 如图 
![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/57ce7760-629d-4ec5-851b-1b790d3b022a)
2. 如图
![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/1d35c898-8aa4-46f8-b4a2-4a9aadbd8ea7)
```
async function operator(proxies = [], targetPlatform, context) {
  const subName = 'a' // 优先
  const fallbackSubName = 'b' // 如果优先不存在就使用这个

  if (proxies.some(p => p.subName === subName)) {
    return proxies.filter(p => p.subName === subName)
  } else {
    return proxies.filter(p => p.subName === fallbackSubName)
  }
}

```
