### ISSUE TITLE
日志优化

### ISSUE THREAD

**Issue by armful5862** [sub-store-org/Sub-Store#303]
当前使用了节点测活和GPT 检测脚本之后,如果节点非常多的话会导致日志飞速刷新

为避免这个问题我将日志重定向到 /tmp/Sub-Store.log

但这样就不能很方便的查看日志

能不能在网页端查看日志?

比如在设置里放一个入口直接来访问

或者支持 在当前路径后面加上/Sub-Store.log 来访问 就像访问/api/utils/env 一样?

**Comment by xream** [comment]
不觉得这是本项目应该做的事情. 你都重定向日志了, 直接配合其他方案不就好了吗...

**Comment by armful5862** [comment]
> 不觉得这是本项目应该做的事情. 你都重定向日志了, 直接配合其他方案不就好了吗...

因为不会😂全程问gpt的,部署在免费容器平台上,折腾到这一步问gpt也不知道怎么继续问了,给出的方案就是重定向

**Comment by xream** [comment]
建议你明确一下自己的需求和遇到的问题, 而不是提出一个具体的做法.
