### ISSUE TITLE
刷新订阅时如何缓存资源

### ISSUE THREAD

**Issue by kien8995** [sub-store-org/Sub-Store#304]
我想在调用函数`operator(proxies) {}`时缓存一些资源，我使用`$substore.write()`。 当我单击刷新按钮时，函数`operator`是否被调用？ 或者你有另一种方法可以在 javascript 中做到这一点吗？

![abd54c88b8e917b74ef8](https://github.com/sub-store-org/Sub-Store/assets/10568426/79bd4107-6c4d-422d-8d08-26994beb7207)

**Comment by xream** [comment]
1. 图中的按钮是刷新订阅流量信息的按钮
2. 没看懂你的需求. 你的问题是 "如何进行缓存的读写"?

**Comment by kien8995** [comment]
我想将域查找结果缓存在`proxy.server`中（示例键值对：domain.com：192.168.0.1）。 但是当域数量太多时会超时，所以我想缓存它们

**Comment by xream** [comment]
参考 https://github.com/xream/scripts/tree/main/surge/modules/sub-store-scripts/check 里的脚本.
里面用到了 `const cache = scriptResourceCache`

**Comment by kien8995** [comment]
`scriptResourceCache`位于哪里

**Comment by xream** [comment]
https://github.com/xream/scripts/blob/main/surge/modules/sub-store-scripts/check/availability.js#L26

读取 `cache.get(id)`

设置 `cache.set(id, {})`

**Comment by kien8995** [comment]
太感谢了
