### ISSUE TITLE
请问一下passwall用哪个订阅格式？

### ISSUE THREAD

**Issue by ceozero** [sub-store-org/Sub-Store#305]
通用订阅获取不到节点，使用v2ray订阅可以获取到节点，但是获取到SS节点后会在端口号后面加到   ”\“
是我的姿势不对么？

![image](https://github.com/sub-store-org/Sub-Store/assets/22513657/d0ac5e2d-f195-4ac1-8938-a18e83d850b7)

**Comment by ceozero** [comment]
补充下版本
前端 v2.14.214
后端 v2.14.266
pass wall：【 4.76-1 】

**Comment by xream** [comment]
不用 passwall 不知道你能否提供日志. 我觉得可能是因为你用的是通用订阅, 而 passwall 请求的 user-agent 不被支持. 建议尝试使用指定目标的链接: 
<img width="265" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/2ceb9b18-a5c3-4db0-a792-c025c98402ac">

**Comment by xream** [comment]
补充一下:

方式 1: PassWall 里指定 User-Agent 比如 `v2ray` 来让 Sub-Store 通用链接输出 v2ray 格式
![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/c1be5f46-b7ea-4e3b-b67e-ad4f2c0bfa2c)

方式 2: Sub-Store 里选择一个输出(必须是 PassWall 支持的) 例如上一个 comment 里的 V2Ray
