### ISSUE TITLE
关于VPS部署安全性

### ISSUE THREAD

**Issue by GD2021** [sub-store-org/Sub-Store#306]
请问部署在VPS上，如何防止被爬取/被盗
有防护规则推荐吗？

**Comment by GD2021** [comment]
![image](https://github.com/sub-store-org/Sub-Store/assets/81171294/cdc32db7-f7a4-4007-8934-9d7901199882)

导入Clash Verge时出现这个

**Comment by xream** [comment]
使用 HTTPS + 复杂的路径 之后, 应当认为安全性与私有 Gist 相当吧. 
可以考虑在反代那边限制拉取客户端的 User-Agent
