### ISSUE TITLE
UI显示不全？

### ISSUE THREAD

**Issue by AlanNandy** [sub-store-org/Sub-Store#309]
请问为啥没有添加按钮咧，使用surge模块在shadowrocket中导入的：
![image](https://github.com/sub-store-org/Sub-Store/assets/29320555/df812436-712d-497e-896e-b90f4f356cc5)

**Comment by xream** [comment]
无效反馈

**Comment by AlanNandy** [comment]
已解决，换用旧版本正常

**Comment by xream** [comment]
@AlanNandy 我猜你是用的带参数版的 Surge 模块. 我已更新文档上的链接
