### ISSUE TITLE
订阅多次请求设置

### ISSUE THREAD

**Issue by utopeadia** [sub-store-org/Sub-Store#311]
订阅多次请求导致订阅被机场封禁。从日志中可以看到产生了大量订阅，同时机场后台也看到同一时间的巨量订阅，请问有没有设置能够限制订阅次数
![image](https://github.com/sub-store-org/Sub-Store/assets/98788152/85b6b9f3-3ac7-447f-b7d0-cc3729940e35)

**Comment by xream** [comment]
@utopeadia 请提供 Sub-Store 同一时间大量请求的证据

**Comment by utopeadia** [comment]
> @utopeadia 请提供 Sub-Store 同一时间大量请求的证据

调查了两家机场的订阅记录，都是同一时间的多次请求
![image](https://github.com/sub-store-org/Sub-Store/assets/98788152/ddffc4fb-359b-4dc2-8354-0ac2cd38f64e)

**Comment by xream** [comment]
@utopeadia 麻烦提供 Sub-Store 端的日志。目前 Sub-Store 没有重试机制也不会主动多次频繁请求。

**Comment by utopeadia** [comment]
> @utopeadia 麻烦提供 Sub-Store 端的日志。目前 Sub-Store 没有重试机制也不会主动多次频繁请求。

我试试能否复现问题

**Comment by utopeadia** [comment]
> @utopeadia 麻烦提供 Sub-Store 端的日志。目前 Sub-Store 没有重试机制也不会主动多次频繁请求。

我想可能跟获取流量信息有关，单词同步除了更新节点外会分别使用HEAD和GET获取流量信息，也就是相当于单同步进行了3次请求，如果调整配置并进行修改的话可能增加到短时间9-12次请求。我用到的机场限制了10次/小时。请问下有办法修改流量同步频率吗

**Comment by xream** [comment]
@utopeadia 请问你的订阅流量信息正常吗 通常情况下 拉取节点信息时会缓存订阅流量信息。如果你日志里有连续的head和get获取流量信息的日志， 说明获取有问题。可以直接加上参数禁用流量获取，例如 http://a.com?token=1#noFlow

**Comment by utopeadia** [comment]
> @utopeadia 请问你的订阅流量信息正常吗 通常情况下 拉取节点信息时会缓存订阅流量信息。如果你日志里有连续的head和get获取流量信息的日志， 说明获取有问题。可以直接加上参数禁用流量获取，例如 http://a.com?token=1#noFlow

感谢，应该是这个问题
