### ISSUE TITLE
节点操作增加收起/展开按钮 优化建议

### ISSUE THREAD

**Issue by jockstrap1044** [sub-store-org/Sub-Store#313]
节点操作增加收起/展开按钮 这个功能很好用，但有一个问题，如果我的节点操作里有多个脚本操作，那么折叠后仅会显示【脚本操作】，能对这个优化一下吗？还有常用配置能否也改成 收起/展开按钮 这样的形式？

**Comment by jockstrap1044** [comment]
1. 加一个小图标点击的时候可以预览?
2. 对的 就是这个意思

**Comment by xream** [comment]
1. 先做了一个节点操作支持单项展开/收起 (`2.14.222`)
2. 常用配置设置完之后 很少需要改动 暂不考虑
