### ISSUE TITLE
使用nginx转发缓存问题

### ISSUE THREAD

**Issue by mrsbCN** [sub-store-org/Sub-Store#317]
我尝试在同一个域名下使用不同的子目录，/导向Sub-Store ， /panel/导向xui。当我访问过/之后，再访问 /panel/，仍然会进入到Sub-Store，但由于Sub-Store底下没有/panel/目录，所以会出现Sub-Store的404。尝试将其他应用放在/时候没有该问题，请问如何解决，底下是location部分的配置。
		  location /panel/ {
            proxy_pass https://127.0.0.1:2053/panel/;
            proxy_set_header Host $host;
            proxy_redirect  off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			}
		  location / {
            proxy_pass http://127.0.0.1:3001/;
            proxy_set_header Host $host;
            proxy_redirect  off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			}

**Comment by xream** [comment]
看着像 PWA 中的问题. 前端 `navigateFallbackDenylist` 规则是 `/(^|\/.+)\/(api|download)\/.+/`.
可能的解决方法: 
1. 修改 `navigateFallbackDenylist` 配置并重新编译前端
2. 不要用 `/panel`, 凑一下上面的规则, 用 `/api/xxx` 或 `/download/xxx` 之类的
3. 不使用 PWA
...

**Comment by mrsbCN** [comment]
非常感谢您回复。仅修改navigateFallbackDenylist还是会有异常，我将底下的runtimeCaching也改成NetworkOnly之后就完全解决了。
