### ISSUE TITLE
参数优化建议

### ISSUE THREAD

**Issue by armful5862** [sub-store-org/Sub-Store#321]
当前支持的参数越来越多，也越来越强大，但使用多个参数就很不方便，大佬有优化的计划吗？

比如将一些常用参数添加一个开关直接可以追加，省去每次填写和手动修改

比如 validCheck，noFlow，hideExpire，showRemaining，noCache，这几个可以直接使用的参数修改成按钮开关的形式，放到常用配置里？

至于cacheKey，flowUserAgent，resetDay，startDate，cycleDays，这些需要赋值的参数考虑用别的方式？

仅做一个参考思路，给大佬递茶🍵

**Comment by xream** [comment]
@armful5862 嗯 多行链接编辑 参数可视化 但是感觉使用频率很低 暂时先不做(
