### ISSUE TITLE
订阅链接响应失败时如何返回代理缓存

### ISSUE THREAD

**Issue by kien8995** [sub-store-org/Sub-Store#323]
我有单个订阅并已经设置了cacheKey，但由于某种原因，订阅链接无法获取节点。 所以我想返回缓存，当前子存储返回错误 500。（我已经检查了 persistenceStore 并且它有一个缓存）

它在预览中返回零节点
![Screenshot 2024-05-14 at 7 21 18 PM jpeg](https://github.com/sub-store-org/Sub-Store/assets/10568426/db73b66a-115b-4fcc-835b-8849441386ed)

并在surge应用程序中更新时返回错误500
![Screenshot 2024-05-14 at 7 24 14 PM jpeg](https://github.com/sub-store-org/Sub-Store/assets/10568426/92ed0b2f-5d8b-4f07-8614-c63d6c577f86)

**Comment by xream** [comment]
<img width="479" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/5342b0b4-9c2c-4357-8cc6-13f0d8e4f9de">
方便的话, 如图导出发我试试. telegram: @xream 或 邮箱 xreamxu@gmail.com
