### ISSUE TITLE
如何会用脚本给订阅额外添加一个自己的节点

### ISSUE THREAD

**Issue by qiaoyun680** [sub-store-org/Sub-Store#326]
您好，我有一个机场订阅了clashmeta的链接，我想通过脚本添加一个自己的wireguard的节点，我应该如何操作呢？
目前我在这个function operator(proxies, targetPlatform) 函数中操作proxies数据没有生效，并且在函数中加入了console.log发现后端也没有打印相应的数据，我是哪里的操作有问题吗？盼您指导一下 感谢

**Comment by xream** [comment]
1. 最简单的方法 如图 加上本地和远程, 然后合并
![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/cd28293c-0748-463e-afa8-cd6b1311a827)
2. 用脚本 一个示例: 
```async function operator(proxies = [], targetPlatform, context) {
  const other_proxies = ProxyUtils.parse(`
  WARP+ = wireguard,interface-ip=172.16.0.2,interface-ipv6=2606:4700:110:8594:18d8:a284:f362:e52,private-key="____________",mtu=1280,dns=1.1.1.1,dnsv6=2606:4700:4700::1111,keepalive=45,peers=[{public-key="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",allowed-ips="0.0.0.0/0,::/0",endpoint=162.159.195.8:2408,reserved=[1,216,39]}]
  `)
  proxies.push(...other_proxies)
  return proxies
}
```

**Comment by xream** [comment]
补充一个 `Sub-Store` 中各种 `WireGuard` 输入/输出格式的说明:  https://t.me/zhetengsha/1144

**Comment by qiaoyun680** [comment]
> 1. 最简单的方法 如图 加上本地和远程, 然后合并
>    ![image](https://private-user-images.githubusercontent.com/1210282/333405654-cd28293c-0748-463e-afa8-cd6b1311a827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTkwMzgsIm5iZiI6MTcxNjUxODczOCwicGF0aCI6Ii8xMjEwMjgyLzMzMzQwNTY1NC1jZDI4MjkzYy0wNzQ4LTQ2M2UtYWZhOC1jZDZiMTMxMWE4MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMDI0NTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ3ZWJmMDRkNWE5YzJkMmNmY2FhYjljMGJkZjg0NGJkYWI0NGZiNDhjY2M3YTI2ODJkN2NmMzY2ZGE1MTdkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rNP3QfKNmPdELcXHx1PvFgrhKbHb2xd-9pG-NisgTOY)
> 2. 用脚本 一个示例:
> 
> ```
> async function operator(proxies = [], targetPlatform, context) {
>   const other_proxies = ProxyUtils.parse(`
>   WARP+ = wireguard,interface-ip=172.16.0.2,interface-ipv6=2606:4700:110:8594:18d8:a284:f362:e52,private-key="____________",mtu=1280,dns=1.1.1.1,dnsv6=2606:4700:4700::1111,keepalive=45,peers=[{public-key="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",allowed-ips="0.0.0.0/0,::/0",endpoint=162.159.195.8:2408,reserved=[1,216,39]}]
>   `)
>   proxies.push(...other_proxies)
>   return proxies
> }
> ```

十分感谢大佬的指点。请问concole.log我应该在哪里查看呢？调试的时候 十分需要，万分感谢

**Comment by xream** [comment]
@qiaoyun680 app 版就是脚本日志里
node.js 版就是进程日志里
