### ISSUE TITLE
本地订阅增加扫描二维码添加功能

### ISSUE THREAD

**Issue by jaychoubaby** [sub-store-org/Sub-Store#327]
希望增加此功能，本地订阅通过url添加，大概率添加后无法使用，特别是clash转换后

**Comment by xream** [comment]
1. 二维码一般是 URI 输入, 其实 URI 解析一直很蛋疼, 因为有规范在 但是很多开发者都不遵守
2. "大概率添加后无法使用，特别是clash转换后" 是什么意思, 来个可复现的例子

**Comment by jaychoubaby** [comment]
> 1. 二维码一般是 URI 输入, 其实 URI 解析一直很蛋疼, 因为有规范在 但是很多开发者都不遵守
> 2. "大概率添加后无法使用，特别是clash转换后" 是什么意思, 来个可复现的例子

测试了ss和Trojan，通过url添加到本地连接，再通过clash for win添加sub-store订阅链接，无法使用，手动添加ss配置到cfw配置中是能用的。我上tg私给你测试一下吧
