### ISSUE TITLE
使用正则命名来为节点名称添加尾缀时，会添加双倍尾缀

### ISSUE THREAD

**Issue by RayWangQvQ** [sub-store-org/Sub-Store#330]
需求：将名称为`abc`重命名为`abc-test`

正则命名：`(.*) `=> `$1-test`

![image](https://github.com/sub-store-org/Sub-Store/assets/31154238/4c015995-bc93-4a42-8c23-054c331001c1)

结果：abc-test-test

![image](https://github.com/sub-store-org/Sub-Store/assets/31154238/6a9f1a9d-cce9-43c1-a49e-acce2664ee4d)

帮忙看下，是用法不对，还是有什么bug？

谢谢

**Comment by cc63** [comment]
直接将$重命名为-test

**Comment by RayWangQvQ** [comment]
> 直接将$重命名为-test

可以了，🐂🍺！

但我上面的写法为啥double了，咋理解

**Comment by xream** [comment]
有参数的 如图:
<img width="279" alt="image" src="https://github.com/sub-store-org/Sub-Store/assets/1210282/462c6c44-11e8-4032-9bd7-7a1b9fbd4cb5">

**Comment by RayWangQvQ** [comment]
哈哈哈原来有个`/g`，懂了。

感谢2位大佬，close。
