### ISSUE TITLE
vmess解析异常

### ISSUE THREAD

**Issue by zixuan945** [sub-store-org/Sub-Store#331]
原始vmess的uri内容经过base64解码如下`{"ps":"xxx","port":"xxx","id":"xxx","aid":0,"net":"tcp","type":"none","tls":"none","add":"xxx"}`
最新版本的Sub-StoreV2.14.332会错误解析,
```
{
  "name": "xxx",
  "type": "vmess",
  "server": "xxx",
  "port": "xxx",
  "cipher": "auto",
  "uuid": "xxx",
  "alterId": 0,
  "tls": false,
  "network": "http",
  "http-opts": {
    "path": [
      "/"
    ],
    "headers": {}
  },
  "id": 4,
  "subName": "test"
}
```
导致Stash内相关的vmess节点无法连接,手动添加vmess节点,承载网络选择None,节点可以正常使用
https://github.com/sub-store-org/Sub-Store/blob/8cd054502337432f9d4e9c24dc56cd746977ec7a/backend/src/core/proxy-utils/parsers/index.js#L188

https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by zixuan945** [comment]
原来的版本是正常使用的,三四天前突然出现异常

**Comment by xream** [comment]
`2.14.333` 应该修复了(

**Comment by zixuan945** [comment]
> `2.14.333` 应该修复了(

已经修复，感谢🙏
