### ISSUE TITLE
希望「文件管理」也可以使用「订阅管理」中的参数

### ISSUE THREAD

**Issue by Energetic3906** [sub-store-org/Sub-Store#335]
将配置文件存放在像 Gist 或其他远程仓库中的 Clash 用户，配置文件中使用了 `proxy-providers`。然而，当将这些配置文件下载到 Clash 后，发现其中的 URL 响应头缺少 `subscription-userinfo` 信息，导致无法显示机场的流量信息。

现在，将配置文件存放在 Sub-Store 后，希望能够添加类似 `flowUrl` 参数，使得文件的响应头中包含指定 URL 的流量信息。这样，通过使用 Sub-Store 处理后的 URL，其响应头将包含 `subscription-userinfo`，从而能够在 Clash 中正常显示机场的流量信息。

**Comment by xream** [comment]
可以试试 后端 2.14.345 前端 2.14.250

![image](https://github.com/sub-store-org/Sub-Store/assets/1210282/37b66197-6615-47a5-89dd-c5d3cb517b5a)
文件支持设置 查询流量信息订阅链接. 服务器版中使用此链接可在响应中传递订阅流量信息(需新版前端)

**Comment by Energetic3906** [comment]
非常感谢您如此迅速地添加了这个小功能，再次感谢！

我已经正常使用了这个功能，一切运行良好，没有问题。
