### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by CassandraCat** [sub-store-org/Sub-Store#341]
I'm using Surge, and I've deployed sub-store in the Surge module, but when I open the webpage, it shows a network error.
![image](https://github.com/user-attachments/assets/23d4d1f1-840a-450c-b1d3-9918d5c4d7c8)
![image](https://github.com/user-attachments/assets/b1010b63-d6a9-45c3-875a-3091fe79e4d2)

**Comment by xream** [comment]
I have written a troubleshooting guide: 
https://t.me/zhetengsha/1068 . You can refer to it. It’s not in English, so if there are any parts you don’t understand, feel free to ask.
