### ISSUE TITLE
单条订阅 vmess导入的节点 host和servername 不同的域名时，会导致节点不能用

### ISSUE THREAD

**Issue by YonQua** [sub-store-org/Sub-Store#345]
单条订阅 vmess导入的节点 host和servername 不同的域名时，转换的域名的servername和SNI 会默认为host的值，导致转换后的节点不能用。要换成把 servername和SNI 改回不为host 的域名才能用。

**Comment by xream** [comment]
就是这样的逻辑...
如果觉得有问题, 能否提供相关文档, 我再研究一下...

**Comment by YonQua** [comment]
vmess://eyJ2IjoiMiIsInBzIjoiUm5WbVRscyIsImFkZCI6IjE4MC4yNC4xMTMuNjEiLCJwb3J0IjoiNDQzIiwiaWQiOiJhYzVlYzQ2NS0xNTAxLTQ3ZmQtZTBkZS0xZmEzNjViNWY0MjIiLCJob3N0IjoiYmFpZHUuY29tIiwicGF0aCI6Ii9hYzdlYzI2NCIsIm5ldCI6IndzIiwic2VjdXJpdHkiOiJub25lIiwidGxzIjoidGxzIiwic25pIjoiZ29vZ2xlLmNvbSJ9

上面内容有解码

{"v":"2","ps":"RnVmTls","add":"180.24.113.61","port":"443","id":"ac5ec465-1501-47fd-e0de-1fa365b5f422","host":"baidu.com","path":"/ac7ec264","net":"ws","security":"none","tls":"tls","sni":"google.com"}

如上"host":"baidu.com"和"sni":"google.com"是二个不同的域名，转换后出来的结果是

  - {"name":"RnVmTls","type":"vmess","server":"180.24.113.61","port":443,"cipher":"auto","uuid":"ac5ec465-1501-47fd-e0de-1fa365b5f422","alterId":0,"tls":true,"network":"ws","ws-opts":{"path":"/ac7ec264","headers":{"Host":"baidu.com"}},"udp":true,"servername":"baidu.com"}


都改成了“baidu.com”
{"Host":"baidu.com"}},"udp":true,"servername":"baidu.com"}

**Comment by xream** [comment]
@YonQua 你又说了遍现象 但是没有回答我的问题(

**Comment by YonQua** [comment]
就是转换后导致节点不能用了，sni的值你用host替换了，节点要的值是google.com而不能用host的baidu.com

**Comment by xream** [comment]
@YonQua 是啊 你还是在说现象. 这个在我目前的认知是标准操作. 你提供的是非标节点数据. 目前来看, 你可以用脚本操作自己处理一下(

**Comment by YonQua** [comment]
你直接試試用vmess://eyJ2IjoiMiIsInBzIjoiUm5WbVRscyIsImFkZCI6IjE4MC4yNC4xMTMuNjEiLCJwb3J0IjoiNDQzIiwiaWQiOiJhYzVlYzQ2NS0xNTAxLTQ3ZmQtZTBkZS0xZmEzNjViNWY0MjIiLCJob3N0IjoiYmFpZHUuY29tIiwicGF0aCI6Ii9hYzdlYzI2NCIsIm5ldCI6IndzIiwic2VjdXJpdHkiOiJub25lIiwidGxzIjoidGxzIiwic25pIjoiZ29vZ2xlLmNvbSJ9做单条订阅后查看下对应的鍵值

**Comment by xream** [comment]
![image](https://github.com/user-attachments/assets/5317cfb2-4738-40b6-8079-d3cfdd1eb13c)
![image](https://github.com/user-attachments/assets/5ad6170e-946f-448d-9c5c-23744a3b3a1a)

**Comment by YonQua** [comment]
算了，我生成后手动改sni或servername为原来节点的域名就能用了，因为我的节点套了cdn所以host的值和tls的sni的域名不是同一个，节点信息如下

{"v":"2","ps":"RnVmTls","add":"180.24.113.61","port":"443","id":"ac5ec465-1501-47fd-e0de-1fa365b5f422","host":"baidu.com","path":"/ac7ec264","net":"ws","security":"none","tls":"tls","sni":"google.com"}

转换后tls的sni值会默认改了host的值，我只要手动改回tls原来的sni值就能用了

理论应该很多host和tls的sni值不是同一个域名的节点，转换后应该都是没法用，因为转换时改成这二个值都默认为host的值了

**Comment by xream** [comment]
@YonQua 套 CDN 是常规操作. 就是应该: server 为优选/中选域名/IP, Host 和 sni 为 CDN 域名 的啊

**Comment by YonQua** [comment]
是的，问题是转换后，就都变成了host的值了，上面的vm节点你转换后看下结果

**Comment by xream** [comment]
@YonQua 你再读一遍？

套 CDN 是常规操作. 就是应该: server 为优选/中选域名/IP, Host 和 sni 为 CDN 域名 的

Host 和 sni 本来就是同一个

**Comment by YonQua** [comment]
不良林有一个套gcore教程，

youtube播放地址：https://youtu.be/FT-O4Xd9gTw

我用的就这个教程搭建的host和sni就不是一个值

**Comment by xream** [comment]
@YonQua 这不重要。你用代理app的时候就会发现需要Host 和 sni 为 cdn 域名才能用。非标场景请给文档吧

**Comment by YonQua** [comment]
用的surge和mihomo都要手动改成不同的才能用，直接用sub-store生成订阅的不能用，因为sni的值的host的一样了，原节点信息的是不一样的，算了反正我折腾了半天，发现手动改下就能用了，

**Comment by xream** [comment]
@YonQua 我和群友们之前折腾的套 CDN 的, 全是 我之前说的那种: server 为优选/中选域名/IP, Host 和 sni 为 CDN 域名 的. 没见过你这种要改成不一样的. 可能是我孤陋寡闻了.

**Comment by xream** [comment]
总结一下就收了吧:
1. Sub-Store 认为 Host 优先. 通常情况下没有问题. 例如常规套 CDN 时: `server` 为优选/中选域名/IP, `Host` 和 `sni` 为 CDN 域名.
2. 其他情况可以用脚本操作自己处理. 如果能提供文档, Sub-Store 可以改一下.

**Comment by YonQua** [comment]
前面发的不良林的教程，你可以过一眼，搭建出来的节点优选后，server 为优选/中选域名/IP, Host 和 sni 都为不同的值。
三个值都为不一样的

**Comment by xream** [comment]
@YonQua 我上面不是写了吗...
我和群友们之前折腾的套 CDN 的, 全是 我之前说的那种: server 为优选/中选域名/IP, Host 和 sni 为 CDN 域名 的. 没见过你这种要改成不一样的. 可能是我孤陋寡闻了. 
其他情况可以用脚本操作自己处理. 如果能提供文档, Sub-Store 可以改一下. 
你一直跟我说现象. 我难道看不懂字吗...没有文档我为什么要去支持非标准情况...

**Comment by YonQua** [comment]
没事，收了吧，我已知问题所在，我脚本处理下就行了。只是提醒下建议。

**Comment by xream** [comment]
> 转换的域名的servername和SNI 会默认为host的值
> 要换成把 servername和SNI 改回不为host 的域名才能用
> sni的值你用host替换了

复盘一下这个问题. 当时围绕上面前提展开了讨论. 所以没得出正确的结论.
其实是 `sni` 参数未取到. 

而当前 tls 的逻辑: 
1. `无 sni` 且 `server 为域名` 时, `sni` 将被设置为 `server`
2. `无 sni` 且 `server 为 IP` 且 `传输层的 Host 为域名` 时, `sni` 将被设置为 `传输层的 Host`

**Comment by xream** [comment]
`2.14.412` 验证通过
