### ISSUE TITLE
请问有没有Loon中资源解析器的参数使用说明？

### ISSUE THREAD

**Issue by PaTTeeL** [sub-store-org/Sub-Store#346]
loon中配置了资源解析器 ：https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-parser.loon.min.js
然后也在订阅节点中开启了资源解析器，目前是可以正常解析订阅的，但是想在解析的时候使用参数筛选掉一部分不想要的节点，参考了qx资源解析器的用法，尝试过 `”订阅链接“#in=CA`  `#in=CA` `in=CA` `#regex=CA` `regex=CA`等各种方式，发现都是没有效果的，notion上的教程也读过了，貌似只有gui方面的操作指南，请教哪里有loon资源解析器的参数用法？

**Comment by xream** [comment]
@PaTTeeL 没有这种功能. 建议在 GUI 统一维护

**Comment by PaTTeeL** [comment]
那"参数"这一行的作用是什么呢？

**Comment by xream** [comment]
支持自定义 ua 和 timeout 等

**Comment by PaTTeeL** [comment]
> 支持自定义 ua 和 timeout 等

可以介绍一下自定义ua和timeout的参数使用方法吗？或者有没有wiki之类的文档可以参考一下？

**Comment by xream** [comment]
@PaTTeeL 可以参考 https://t.me/LoonNews/1322
