### ISSUE TITLE
是否考虑支持规则分流

### ISSUE THREAD

**Issue by Asakushen** [sub-store-org/Sub-Store#348]
类似于订阅转换的功能，支持导入自定义的规则进行生成带分流的订阅链接？

**Comment by xream** [comment]
暂不考虑 可使用文件功能:
生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)

**Comment by Asakushen** [comment]
> 暂不考虑 可使用文件功能: 生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)
> 
> Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)
> 
> 生成 sing-box 配置 (https://t.me/zhetengsha/1070)
> 
> 生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)

谢谢解答！太感谢了
