### ISSUE TITLE
【BUG】组合订阅内容不一致

### ISSUE THREAD

**Issue by xingxin1590** [sub-store-org/Sub-Store#352]
我的第一个组合订阅内容会自动切换为第二个组合订阅内容
![image](https://github.com/user-attachments/assets/17fc50c4-1223-4286-9624-a0feada5d2d6)
![image](https://github.com/user-attachments/assets/01accf3a-4d7f-44ca-bd47-8718d4345add)
从图片可以看出，节点内容不一致

**Comment by xream** [comment]
目测是误用 `cacheKey` 导致的

`2.14.382` 增加了一个日志报错

使用自定义缓存时 `cacheKey` 的值不能为空
