### ISSUE TITLE
Mac Surge 配置完成sub-store后“主窗口”-“事件”提示WARN

### ISSUE THREAD

**Issue by oslytherin** [sub-store-org/Sub-Store#354]
Mac Surge 配置完成sub-store后“主窗口”-“事件”提示：WARN  Sub-Store模块包含了一条使用了未知策略的规则：DOMAIN,sub-store.vercel.app,PROXY #!FROM-MODULE:Sub-Store，请问这是什么情况？怎么解决呀？
![iShot_2024-09-20_08 43 04](https://github.com/user-attachments/assets/c56e3073-e225-4ed9-9e7a-c29f2595f1c6)

**Comment by xream** [comment]
@oslytherin 盲猜你误用了loon 插件， 请检查是否使用了正确的官方 surge 模块

**Comment by oslytherin** [comment]
> @oslytherin 盲猜你误用了loon 插件， 请检查是否使用了正确的官方 surge 模块

谢谢，已解决。
