### ISSUE TITLE
【BUG】订阅管理的正则过滤操作在文件管理里不起作用

### ISSUE THREAD

**Issue by xingxin1590** [sub-store-org/Sub-Store#355]
如图我已经将订阅管理正则过滤
![图片](https://github.com/user-attachments/assets/75b14688-a85c-4297-8d1d-154ace790499)
然后导入到文件管理
![图片](https://github.com/user-attachments/assets/967e212c-a61b-4d97-aae9-3a433187c779)
可是发现在文件管理里导出的节点仍然有过滤掉的节点
![图片](https://github.com/user-attachments/assets/a5a3e639-c0c5-41ff-b0d4-745f86d13ddc)

**Comment by xream** [comment]
支持的 可能是缓存
