### ISSUE TITLE
【Feature】希望把节点前添加旗帜的操作脚本更新一下

### ISSUE THREAD

**Issue by xingxin1590** [sub-store-org/Sub-Store#356]
后端更新之后，原来的脚本操作不能正常使用了
https://github.com/sub-store-org/Sub-Store/blob/master/scripts/ip-flag-node.js

**Comment by xream** [comment]
无法复现. 请提供复现方法

**Comment by xingxin1590** [comment]
> 无法复现. 请提供复现方法

Error: connect ETIMEDOUT 198.18.0.26:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '198.18.0.26',
  port: 80

以上是终端启动后的报错提示

**Comment by xream** [comment]
非 Sub-Store 或脚本的问题
