### ISSUE TITLE
Please support new ss protocol for surge Mac

### ISSUE THREAD

**Issue by hungrybirder** [sub-store-org/Sub-Store#359]
![CleanShot 2024-10-15 at 19 52 10@2x](https://github.com/user-attachments/assets/e3f145a0-a201-41de-b477-fac2ae993f8b)

**Comment by xream** [comment]
https://t.me/cool_scripts/621

**Comment by hungrybirder** [comment]
> https://t.me/cool_scripts/621

Thank you. It works
