### ISSUE TITLE
文件管理获取远程文件希望增加Header

### ISSUE THREAD

**Issue by ChrisLee0** [sub-store-org/Sub-Store#360]
我想在文件管理中调用Surge API获取当前profile，并同步到gist，但是surge http api需要传入header X-Key，导致无法获取。希望获取远程文件时增加header

**Comment by xream** [comment]
可以考虑. 但是你这个需求完全可以用脚本实现. 甚至获取本机 profile 不需要 X-Key
<img width="561" alt="image" src="https://github.com/user-attachments/assets/39e000f8-7b16-4c84-9825-5d1523bc0fda">

**Comment by ChrisLee0** [comment]
成功了，感谢大佬
