### ISSUE TITLE
订阅链接vless节点里面的sni参数错误

### ISSUE THREAD

**Issue by lengxii** [sub-store-org/Sub-Store#361]
通过sub store生成的订阅链接vless节点里面的sni域名会变成节点的域名，正常我设置的是www.yahoo.com域名，
然后导入v2rayn 因SIN 不正确会导致节点无法使用
导入clash没有显示SNI参数，看了下servername的参数正确应该是www.yahoo.com ，但是它会变成服务器节点域名，导致节点无法使用
这是sub store生成的通用订阅链接：
`[
    {
        "name": "韩国首尔vless",
        "type": "vless",
        "server": "sr.123456.xyz",
        "port": 30000,
        "uuid": "d07ba1eb-00d1-4f97-ba95-efc0552fc005",
        "alterId": 0,
        "cipher": "auto",
        "udp": true,
        "flow": "xtls-rprx-vision",
        "tls": true,
        "servername": "www.yahoo.com",
        "reality-opts": {
            "public-key": "kS-Q_WGqJsvTUkZO4ax6LO55BJyGZNfly8lrhR3M",
            "short-id": "25faadf2"
        },
        "client-fingerprint": "qq",
        "network": "tcp",
        "sni": "sr.123456.xyz",
        "_subName": "lengxi",
        "_subDisplayName": ""
    },`

正常 sni 应该是www.yahoo.com才对，我是Vless+reality+xtls-rprx-vision的组合方式，  这个组合不需要服务器节点有域名证书
![image](https://github.com/user-attachments/assets/7bf55da8-5ca0-49dc-bf6d-452c47e24473)

**Comment by xream** [comment]
麻烦给一下输入的原始内容. 还有确认下后端版本. 是不是用的旧版.

**Comment by qiuligao01** [comment]
我也遇到这样的问题，转换之后sni变成了host的ip，导致节点无法使用只有将sni设置成cdn的域名，我这里是apple.com才可以，用的最新版本的后端

后端版本号为v2.21.19,原始内容：{"name":"US-RK-VLESS-Vision-Reality-ZJ","type":"vless","server":"142.115.42.17","port":3143,"udp":true,"uuid":"99994961-bb92-4bd4-953c-046b6840702c","flow":"xtls-rprx-vision","packet-encoding":"xudp","tls":true,"client-fingerprint":"chrome","sni":"updates.cdn-apple.com","server_name":"updates.cdn-apple.com","reality-opts":{"public-key":"anL0trWbAUzATS1pjvA9OvbZocJ8YVWK1oY-lTIeLXo","short-id":"34e7713e52bf88a9"},"skip-cert-verify":false,"network":"tcp"}，转换之后节点显示，使用的是singbox{
  "outbounds": [
    {
      "tag": "US-RK-VLESS-Vision-Reality-ZJ",
      "type": "vless",
      "server": "142.115.42.17",
      "server_port": 3143,
      "uuid": "99994961-bb92-4bd4-953c-046b6840702c",
      "tls": {
        "enabled": true,
        "server_name": "142.115.42.17",
        "insecure": false,
        "reality": {
          "enabled": true,
          "public_key": "anL0trWbAUzATS1pjvA9OvbZocJ8YVWK1oY-lTIeLXo",
          "short_id": "34e7713e52bf88a9"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "flow": "xtls-rprx-vision"
    }
  ]
}

**Comment by xream** [comment]
> 我也遇到这样的问题，转换之后sni变成了host的ip，导致节点无法使用只有将sni设置成cdn的域名，我这里是apple.com才可以，用的最新版本的后端
> 
> 后端版本号为v2.21.19,原始内容：{"name":"US-RK-VLESS-Vision-Reality-ZJ","type":"vless","server":"142.115.42.17","port":3143,"udp":true,"uuid":"99994961-bb92-4bd4-953c-046b6840702c","flow":"xtls-rprx-vision","packet-encoding":"xudp","tls":true,"client-fingerprint":"chrome","sni":"updates.cdn-apple.com","server_name":"updates.cdn-apple.com","reality-opts":{"public-key":"anL0trWbAUzATS1pjvA9OvbZocJ8YVWK1oY-lTIeLXo","short-id":"34e7713e52bf88a9"},"skip-cert-verify":false,"network":"tcp"}，转换之后节点显示，使用的是singbox{ "outbounds": [ { "tag": "US-RK-VLESS-Vision-Reality-ZJ", "type": "vless", "server": "142.115.42.17", "server_port": 3143, "uuid": "99994961-bb92-4bd4-953c-046b6840702c", "tls": { "enabled": true, "server_name": "142.115.42.17", "insecure": false, "reality": { "enabled": true, "public_key": "anL0trWbAUzATS1pjvA9OvbZocJ8YVWK1oY-lTIeLXo", "short_id": "34e7713e52bf88a9" }, "utls": { "enabled": true, "fingerprint": "chrome" } }, "flow": "xtls-rprx-vision" } ] }

你字段写错了. 是 `servername` 不是 `server_name`...写错了能对吗

**Comment by qiuligao01** [comment]
明白了，谢谢大佬，改成servername，我又回去看了，正常输出了
