### ISSUE TITLE
无效的API地址，请检查

### ISSUE THREAD

**Issue by Fablics** [sub-store-org/Sub-Store#362]
现在使用插件会显示下图：
![image](https://github.com/user-attachments/assets/e2165d07-d428-4ce7-a086-7420e2a72411)

问题的出现是有一天打开，弹相似的红色窗口，提示后端无法连接（我没做自建，一直是跟随默认设置直接用。当时看了弹窗提示，进入了设置>后端设置，看到有两个，一个是默认，一个是http:xxx，将当时正在使用的删掉了，切换到默认）
![image](https://github.com/user-attachments/assets/b9fb4418-08e3-4077-9df9-97aabd542046)

这以后仍不能使用。所以尝试重装插件和软件，仍显示api问题。

我该如何使他复原？或者全新安装/运行，以覆盖我删除当时后端的操作？
感谢大佬。

**Comment by PDxtXHd** [comment]
本来就不提供后端，默认后端是给APP用户的，指向的是APP自己的后端，你之前能用是蹭到了别人的后端

**Comment by xream** [comment]
排查:
https://t.me/zhetengsha/1278
https://t.me/zhetengsha/1068
