### ISSUE TITLE
VLESS mKcp 解析错误

### ISSUE THREAD

**Issue by YanG-1989** [sub-store-org/Sub-Store#363]
自建节点 vless-mKcp  
处理后变成 vless-tcp  

导致节点失效...

**Comment by xream** [comment]
@YanG-1989 来个可复现的例子

**Comment by YanG-1989** [comment]
补充说明，3x面板搭建，ShadowRocket使用。

**Comment by YanG-1989** [comment]
> 已更新 麻烦试试 `2.14.403`
> 
> 
> 
> 说明一下: 
> 
> 
> 
> 1. "自建节点 vless-mKcp 处理后变成 vless-tcp" 的表述不正确. 实际表现: 未处理 `network` 为 `kcp` 时的 `seed` 和 `headerType` 字段. 如果能提供脱敏的原始输入, 现状 和 期望表现, 会更清晰直接
> 
> 
> 
> 2. 使用 3x-ui 面板搭建搭建并导出订阅链接并非是标准操作. 3x-ui 有使用非标 URI 的前科. 应以官方规范为准, 辅助部分必要的非标兼容.
> 
> 
> 
> 3. 使用 Shadowrocket 测试不严谨. Shadowrocket 也喜欢非标

原来如此😂...晚上我去试下..谢谢
到时候反馈

**Comment by YanG-1989** [comment]
经过测试 v2rayNG  转换订阅后正常 (之前没测试过订阅地址), 小火箭 还是不正常，参数传递应该遗漏或者错误。

下面是链接解析后的数据:
vless://：协议类型，表示使用的是 VLESS。
3df5ed42-d821-4cf7-9287-15ed12da5b9a：这是 UUID，用户的唯一标识符。
199.99.99.999：服务器的 IP 地址。
20222：服务器端口。
?type=kcp：传输协议类型，表示使用 KCP 协议。
headerType=none：KCP 的数据头类型为 none，不使用额外的数据包头。
seed=kwDVbRU1pS：KCP 的种子，用于 KCP 数据加密。
security=none：不使用额外的安全加密措施。
#我是超人：链接名称。
--------------------------------------------------------------------------------------
如果还需要提供什么信息..请留言.

**Comment by xream** [comment]
直接用确实是不行的
因为为了兼容行 给 Shadowrocket 的其实是微调的 clash.meta(mihomo) 订阅.
里面没有定义 mKcp
你要用的话 就给 Shadowrocket 也用 `?target=V2Ray` 的

**Comment by YanG-1989** [comment]
> 直接用确实是不行的
> 
> 为了兼容性 给 Shadowrocket 的其实是微调的 clash.meta(mihomo) 订阅.
> 
> 里面没有定义 mKcp
> 
> 你要用的话 就给 Shadowrocket 也用 `?target=V2Ray` 的

ok 解决了..感谢 订阅加上`?target=V2Ray` 解决了！
