### ISSUE TITLE
Sub-Store 下载订阅失败 X 无法下载订阅：chne！ 原因：undefined is not an object （evaluating 'e.length"）

### ISSUE THREAD

**Issue by jochne** [sub-store-org/Sub-Store#365]
![CleanShot 2024-10-29 at 10  51 51@2x](https://github.com/user-attachments/assets/a596374e-06b7-4005-83f7-5a26a53cd32e)

不确定是不是这个订阅是ssr协议导致的，使用了mihomo来替换服务

$server._exec = '/usr/local/bin/mihomo'

**Comment by xream** [comment]
<img width="322" alt="image" src="https://github.com/user-attachments/assets/43bf46c9-7274-4b71-9315-06e024e76072">
私我个复现方式吧

**Comment by jochne** [comment]
初步定位问题原因，使用mihomo的订阅地址，末尾一定要加 `target=SurgeMac`  参数
