### ISSUE TITLE
关于VMESS 里SNI 的错误

### ISSUE THREAD

**Issue by wangjj9219** [sub-store-org/Sub-Store#366]
我用了自己的订阅链接，但是发现 sub  store 总会把我的SNI 改成server name ,实际应该是host , 怎么解决，vless没有这个问题，vmess 有这个问题

**Comment by xream** [comment]
我记得修复过了...来个例子?

**Comment by xream** [comment]
当前 tls 的逻辑: 
1. `无 sni` 且 `server 为域名` 时, `sni` 将被设置为 `server`
2. `无 sni` 且 `server 为 IP` 且 `传输层的 Host 为域名` 时, `sni` 将被设置为 `传输层的 Host`

**Comment by xream** [comment]
顺便 有点没看懂你的表达.
我先说明一下几个概念
1. VMess 的 `servername` 字段在解析的过程中, 会变成 Sub-Store 内部统一的字段 `sni`
2. 如有需要, 可以使用脚本操作 修改 `sni`
3. 转换到对应目标时, 会变成对应的字段, 例如 `servername`

**Comment by xream** [comment]
如果是 VMess URI 输入 请尝试 `2.14.412`
