### ISSUE TITLE
自己开发更新脚本时，该如何避免远程脚本缓存造成脚本未更新

### ISSUE THREAD

**Issue by qixing-jk** [sub-store-org/Sub-Store#367]
自己开发脚本的时候，脚本GitHub更新了，但是后端一直还是使用的脚本缓存，除非手动使用commit版本的
该如何手动刷新掉脚本缓存呢？

**Comment by xream** [comment]
前端左上角刷新. 或者给脚本加个 #noCache 总是不使用缓存. 或者简单的改下 ?v=1 之类的

**Comment by qixing-jk** [comment]
> 前端左上角刷新. 或者给脚本加个 #noCache 总是不使用缓存

这里的缓存刷新和不使用是指所有缓存嘛

我调试完毕后，肯定还是使用原来的URL（GitHub指向最新提交的文件），那还会有缓存，那这种脚本缓存什么时候会自动失效？

**Comment by xream** [comment]
1. 前端左上角刷新会清所有缓存.
2. 48小时

其实还好. 调试的时候加上 #noCache
完成后 删掉 #noCache
着急的话 自己加个无意义的 query 比如 ?v=1 就行
