### ISSUE TITLE
本地编写脚本时，如何使用本地脚本进行调试并支持URL参数

### ISSUE THREAD

**Issue by qixing-jk** [sub-store-org/Sub-Store#368]
拉取远程脚本方式较为麻烦，是否有方式能够支持本地调用脚本进行快速测试，最好能够支持URL参数，调试完毕再上传GitHub等地方
并且使用mihomo-party的方式应该如何查看脚本调试日志

**Comment by xream** [comment]
1. 使用文件功能. 创建的文件可以在脚本操作中使用
2. mihomo-party 如何查看脚本调试日志请咨询 mihomo-party

**Comment by qixing-jk** [comment]
Failed to preview collection
type: InternalServerError
Reason: 脚本操作 执行 function operator 失败 Unexpected token '*'; 执行快捷脚本 失败 Invalid or unexpected token
是否文件名最后要带文件扩展名，使用.js结尾时正常，但不使用则会报上方错误

**Comment by xream** [comment]
那肯定是完整的 直接是用的文件的名称 `name`
