### ISSUE TITLE
ios版Surge更新到5.14.0（Build3367）后爆内存

### ISSUE THREAD

**Issue by Bigbrother84844** [sub-store-org/Sub-Store#370]
ios版Surge更新到5.14.0（Build3367）后爆内存，只要刷新substore，surge就会关闭后重启。每日定时23：55自动刷新倒是可以成功。
日志只有substore simple和sync，没有core，应该是core无法启动？surge没更新前从来没遇到这个问题。关闭其他模块，只留substore一个模块也会爆内存，请问如何解决？

系统：18.1
substore模块用的是官方默认版。

**Comment by xream** [comment]
刷新 Sub-Store 前端的时候确实没有 core 吧. 可以看看 simple 的日志.

可以依次尝试以下办法:

1. 可能是首页的并发请求太多. 最近前端改了一下这里的逻辑
尝试这次操作: 
删除桌面图标
关掉浏览器 tab
杀掉浏览器后台
重新打开浏览器
输入 https://sub-store.vercel.app/aboutUs?api=https://not-sub.store
这里故意设置了一个错误的后端. 目的是先不管后端的问题, 先刷新出前端
最新版前端版本号是 `2.14.283`
刷新出最新版后 重新进去 https://sub-store.vercel.app?api=https://sub.store 确认是否正常

2. 可能是订阅太大了, 写入缓存的时候爆了. 可以尝试在 Surge 的脚本编辑器里执行
```
const data = JSON.parse($persistentStore.read('sub-store'))
data.settings.cacheThreshold = "1024"
$persistentStore.write( JSON.stringify(data), 'sub-store')
$done({ok: 1})
```
这样会设置阈值为 1024

**Comment by xream** [comment]
补充一个信息: 最近有群友反馈有机场更换了订阅的域名, 老订阅链接会被重定向到一个 10G 大小的文件...你其实可以自己看最近请求

**Comment by Bigbrother84844** [comment]
感谢大佬赐教，根据方法1成功了，谢谢~

**Comment by yks2024** [comment]
感谢大佬赐教，根据方法成功解决问题，谢谢大佬~~~
