### ISSUE TITLE
订阅链接为文件或base64内容时 报错订阅不含有效内容

### ISSUE THREAD

**Issue by mitlearn** [sub-store-org/Sub-Store#374]
机场提供两种订阅链接
一种为默认 链接打开显示的为base64编码后的信息 Clash-verge中可以导入和使用 sub-store拉取时提示如下

> {"status":"failed","error":{"code":"INTERNAL_SERVER_ERROR","type":"InternalServerError","message":"Failed to download subscription: *****","details":"Reason: 订阅 ***** 中不含有效节点"}}

尝试过添加ua 例如`clash.meta` / `clash-verge/v1.7.7` / `surge/3004` 都无法正常获取

另一种为`链接&flag=clash` 链接打开会下载clash配置文件 sub-store拉取时同上提示
> {"status":"failed","error":{"code":"INTERNAL_SERVER_ERROR","type":"InternalServerError","message":"Failed to download subscription: *****","details":"Reason: 订阅 ***** 中不含有效节点"}}

![image](https://github.com/user-attachments/assets/910d42e3-913f-4ad1-b53f-3549e6fc14a4)

是否是我缺少填写了参数导致无法让sub-store获取？

**Comment by xream** [comment]
感觉像是你代理策略的问题. 可以私发我复现下

**Comment by mitlearn** [comment]
> 感觉像是你代理策略的问题. 可以私发我复现下

代理关闭也是一样 verge导入时没有代理

**Comment by xream** [comment]
@mitlearn 嗯 那就私发我复现下

**Comment by mitlearn** [comment]
测试发现可能有缓存干扰 base64可以解析
感谢大佬配合
