### ISSUE TITLE
Subscription Converter转换后的地址导入到Sub-Store后规则信息丢失问题

### ISSUE THREAD

**Issue by zhuqq2020** [sub-store-org/Sub-Store#376]
订阅地址通过Subscription Converter转换后的地址在导入到Sub-Store后，用客户端更新之后规则信息没有了！不知是不是Sub-Store过滤掉的。
版本信息如下
前端 v2.14.298
后端 v2.14.424

**Comment by xream** [comment]
Sub-Store 的订阅功能就是订阅

关于文件:

ℹ️ 生成文件 & 配置

生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)
