### ISSUE TITLE
请教一个WireGuard通过sub-store转成surge订阅链接🔗的问题

### ISSUE THREAD

**Issue by KyleKwan2024** [sub-store-org/Sub-Store#379]
请教一个WireGuard通过sub-store转成Surge IOS上的订阅链接🔗的问题。
本人愚钝，实在看不明白https://t.me/zhetengsha/1144的语法介绍，问了gpt也没问出来什么。
以下面这个WireGuard节点为例，可否帮忙具体教学一下。
谢谢大家。
`wireguard://162.159.195.101?public-key=bmXOCPfgyo=&private-key=cHWy027mL67dk3c=&port=3476&ip=172.16.0.2&mtu=1280&udp=true&reserved=230,253,135
`

**Comment by xream** [comment]
![image](https://github.com/user-attachments/assets/09571288-bbff-4f45-8f73-bedabafc05b6)
<img width="312" alt="image" src="https://github.com/user-attachments/assets/51b85893-ff06-4846-b5dc-c8109401af40">

**Comment by KyleKwan2024** [comment]
> ![image](https://private-user-images.githubusercontent.com/1210282/389248847-09571288-bbff-4f45-8f73-bedabafc05b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjUzMTcsIm5iZiI6MTczMjQyNTAxNywicGF0aCI6Ii8xMjEwMjgyLzM4OTI0ODg0Ny0wOTU3MTI4OC1iYmZmLTRmNDUtOGY3My1iZWRhYmFmYzA1YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjRUMDUxMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ3ZGFjYzFkZmQ2ZjdhMDQ2ZmM3MDYxMGZjM2M1N2E2MDQ2NTFiZGU5MjM4OWEwZjQ2YzA4MWYwMzg1YWFjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YvfNCn38T8JyXgUsAV_uEheHTAXzE6sCgBaKi7k_ANU) <img alt="image" width="312" src="https://private-user-images.githubusercontent.com/1210282/389248844-51b85893-ff06-4846-b5dc-c8109401af40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjUzMTcsIm5iZiI6MTczMjQyNTAxNywicGF0aCI6Ii8xMjEwMjgyLzM4OTI0ODg0NC01MWI4NTg5My1mZjA2LTQ4NDYtYjVkYy1jODEwOTQwMWFmNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjRUMDUxMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTBlZGEzZWY1ZmMyNDQ3ODFlYWE5Y2RiYmU4YTRiNmIwNzBhY2ZkOTdhNmU3NGY3YWUwY2NhN2Q3ZGRhYTk1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FxCBiJvAY67D_tweF7JDYxsnz6-dAYwX6_0dUBlT0bw">

是把这里复制的订阅链接（类似于https://sub.store/download/warp%2B?target=Surge&includeUnsupportedProxy=true）的填入这里吗？
![image](https://github.com/user-attachments/assets/6d91cd40-ae74-4d9b-9842-97687549f102)
![image](https://github.com/user-attachments/assets/2021a2d2-fa58-4613-b3cd-934474202acd)

**Comment by xream** [comment]
要不你看下 Surge 的文档学习一下?
Surge 没法把 WireGuard 直接当成单行节点使用.
所以 Sub-Store 这样的做法是生成一个模块

**Comment by KyleKwan2024** [comment]
> 要不你看下 Surge 的文档学习一下? Surge 没法把 WireGuard 直接当成单行节点使用. 所以 Sub-Store 这样的做法是生成一个模块

好的，谢谢您，我还是土办法，手动填入WireGuard节点吧  :(  。
