### ISSUE TITLE
聚合多个订阅节点，拉取的时候获取的header流量信息不对，默认取了第一个

### ISSUE THREAD

**Issue by geekoutnet** [sub-store-org/Sub-Store#380]
方案1: 建议把所有获取到的单个节点的header 累加 或者单独挨个获取 后再累加
方案1: 聚合订阅中可以单独增加个 "获取流量信息"的功能

**Comment by xream** [comment]
1. 累加的意义是啥
2. 没看懂
要我说组合订阅本来就不应该传递流量信息 没啥意义(

**Comment by geekoutnet** [comment]
累加的意义在于显示准确啊，比如多个订阅 ，所有的total 总流量加一起肯定是和实际差不多的，同理，upload和download 逻辑也是一样的,   要不然拉取聚合订阅的时候流量显示的不正确，看着很难受，也没法监控用了多少啊

**Comment by xream** [comment]
@geekoutnet 能理解 但是不认同

**Comment by xream** [comment]
@geekoutnet 现在远程订阅还支持多个链接。 那一次拉取得把所有的单条订阅里的所有的没加noFlow的订阅都拉一遍 然后加起来，还得处理异常情况（比如去掉负数或者数据异常的）。感觉很不合理。

**Comment by geekoutnet** [comment]
@xream 或者换个思路，简单微调，可以提供一个单独获取订阅流量的url链接也可以的，这样就可以实现自定义的流量显示,  当个扩展也好啊

**Comment by xream** [comment]
@geekoutnet 现在就能实现 把某个单条订阅放到这个组合订阅的第一项...
