### ISSUE TITLE
未启动监听前端端口

### ISSUE THREAD

**Issue by xueqino1** [sub-store-org/Sub-Store#383]
nodejs版本 v20.15.0，win10 操作系统，frontend目录已经放在sub-store.bundle.js 同目录下。启动前设置了环境变量
set SUB_STORE_FRONTEND_BACKEND_PATH=/ZfGq8rJTQApqifhquZqQ
set SUB_STORE_BACKEND_API_HOST=127.0.0.1
set SUB_STORE_BACKEND_API_PORT=3002
set SUB_STORE_FRONTEND_HOST=0.0.0.0
set SUB_STORE_FRONTEND_PORT=3003

node  sub-store.bundle.js 后只输出了如下信息：
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
     Sub-Store -- v2.14.433
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅

[sub-store] INFO: [BACKEND] 127.0.0.1:3002

浏览器访问http://127.0.0.1:3002/ 跳转到https://sub-store.vercel.app/subs，访问http://127.0.0.1:3003无法打开网页，netstat查看，3002在监听，3003未监听

如何debug？

**Comment by xream** [comment]
`SUB_STORE_FRONTEND_PATH` 需要设置为 前端文件夹路径

**Comment by xueqino1** [comment]
谢谢大佬，想当然的以为会找同目录呢，浪费了好几个小时。谢谢。

**Comment by xueqino1** [comment]
谢谢大佬，想当然的以为会找同目录呢，浪费了好几个小时。谢谢。
