### ISSUE TITLE
[BUG]"文件编辑"下面文件响应过滤非2xx的响应

### ISSUE THREAD

**Issue by lakevilladom** [sub-store-org/Sub-Store#386]
新建"文件编辑"：
名称:test
显示名称:TEST
远程链接:https://gist.githubusercontent.com/lakevilladom/ae53fbaa62d526d0c92d37182ca31ec7/raw/test
链接内容：
```
# 测试脚本----->(远程)
async function operator(proxies = [], targetPlatform, env) {
}
```

本地:
```
# 测试脚本----->(本地)
async function operator(proxies = [], targetPlatform, env) {
}
```
合并来源:远程优先
忽略失败的远程文件：是

## BUG
如果远程链接错误，比如：https://gist.githubusercontent.com/lakevilladom/ae53fbaa62d526d0c92d37182ca31ec7/raw/test1
则返回如下内容：
![image](https://github.com/user-attachments/assets/4a024b05-6522-4b3c-b184-e3a5d8b025c8)
> bug说明：这个bug链接里面写错成test1，只是举例，现实情况可能前面加了代理,比如`https://ghp.ci/`，如果代理服务异常可能导致返回异常内容，所以建议对请求响应做判断，过滤非2xx的响应

## BUG2
编辑文件管理的内容，保存后，再次编辑发现内容还是以前的内容，但是刷新页面后就正常显示了，这个问题我最近出现了2次，但是这会儿好像又是正常的

**Comment by xream** [comment]
1. 可尝试 `2.14.439`
2. 疑似 PWA 的问题, 可以尝试清除缓存等操作
<img width="622" alt="image" src="https://github.com/user-attachments/assets/c97809ce-b818-4a76-8e53-26bf8b2dda70" />

**Comment by lakevilladom** [comment]
反馈的bug已解决，目前有个疑问，如果合并来源:远程优先，远程链接正常响应的情况下，返回结果应该是什么样的：
```
# 测试脚本----->(远程)
async function operator(proxies = [], targetPlatform, env) {
}
```
还是
```
# 测试脚本----->(远程)
async function operator(proxies = [], targetPlatform, env) {
}
# 测试脚本----->(本地)
async function operator(proxies = [], targetPlatform, env) {
}
```

**Comment by xream** [comment]
@lakevilladom 远程内容
本地内容

**Comment by lakevilladom** [comment]
Ok,那就我反馈的这个Bug已解决
其实我想利用这儿的"文件"功能实现远程脚本如果拉取失败就用本地脚本，看来这样还不行

**Comment by xream** [comment]
@lakevilladom 那可以用脚本自己写逻辑吧 取不到就用本地的

**Comment by lakevilladom** [comment]
嗯嗯 我试下

**Comment by lakevilladom** [comment]
> @lakevilladom 那可以用脚本自己写逻辑吧 取不到就用本地的

能不能给个用例，我写的脚本，打开文件链接的时候输出的是这个脚本内容本身

**Comment by xream** [comment]
@lakevilladom 
```
$content = $files[0] || $files[1]
```
<img width="2218" alt="image" src="https://github.com/user-attachments/assets/b1c58b61-be1f-43f4-8527-418aaf00489d" />

**Comment by lakevilladom** [comment]
> ```
> $content = $files[0] || $files[1]
> ```

非常感谢！完美解决，顺便再反馈一个小问题：
当我按照这样地址访问的sub-store时候：https://xxx.com/?api=https://xxx.com/，服务正常访问
但是file的完整地址就会是：https://xxx.com//api/file/test.js
访问这个file会报错
![image](https://github.com/user-attachments/assets/9c486c6e-e7e0-4744-9607-05cd47ed9f49)

**Comment by xream** [comment]
应该是没兼容末尾的 `/` 吧. 这个就自己改下吧 不要加 末尾的 `/`

**Comment by lakevilladom** [comment]
嗯嗯，我自己修改了
