### ISSUE TITLE
能否增加按地区自定义排序的功能？

### ISSUE THREAD

**Issue by Eureka-0** [sub-store-org/Sub-Store#388]
想把常用地区的节点排到前面，能否在节点排序里增加一个按地区自定义排序（比如可以给一个地区列表，手动拖拽来自定义顺序）的功能？

**Comment by xream** [comment]
正则排序可以实现.
而且现在节点操作可以复制+导入. 你可以自己维护一个自己的正则排序

**Comment by Eureka-0** [comment]
用正则排序实现了，之前没注意到这个抱歉
