### ISSUE TITLE
Stash 导入： 配置解析错误

### ISSUE THREAD

**Issue by GHParadise** [sub-store-org/Sub-Store#389]
通过订阅--》 预览/拷贝订阅功能， 选择Stash 复制链接，  导入stash 的时候报 配置解析错误
![image](https://github.com/user-attachments/assets/4e38fc44-9700-4b3c-be7c-5828506f0aaa)

**Comment by xream** [comment]
因为不是配置

**Comment by xream** [comment]
若要生成配置. 参考:

ℹ️ 生成文件 & 配置

生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)

**Comment by GHParadise** [comment]
就想意见生成的订阅可以导入到stash 中直接用，  看来还要加工是吧  不能直接导入给stash

**Comment by xream** [comment]
也可以 只是你误把订阅当成配置了

**Comment by xream** [comment]
Stash 配置列表界面, 上面是导入, 下面是创建. 可以自己摸索

**Comment by GHParadise** [comment]
多谢   搞定了
