### ISSUE TITLE
功能请求：文件管理新增文件夹同步

### ISSUE THREAD

**Issue by XYZliang** [sub-store-org/Sub-Store#390]
如题，除了现有的从远程 url 拉取同步文件到 sub-store，能否再支持拉取整个文件夹/git
例如直接拉取整个[ACL4SSR](https://github.com/ACL4SSR/ACL4SSR/tree/master)、[meta-rules-dat](https://github.com/MetaCubeX/meta-rules-dat)到sub-store，方便rule-providers从sub-store拉取相关配置，而不是从其他不一定稳定的 github 镜像站

**Comment by xream** [comment]
有点怪. 你这种环境肯定是 Node.js 版了. 我觉得你完全可以自己外部处理.

**Comment by XYZliang** [comment]
> 有点怪. 你这种环境肯定是 Node.js 版了. 我觉得你完全可以自己外部处理.

自己处理肯定是没问题，只是突发奇想毕竟是文件管理，再多做一步把文件夹这种弄上更方便了哈哈哈省的自己实现
