### ISSUE TITLE
sock5 代理无法正常使用

### ISSUE THREAD

**Issue by XYZliang** [sub-store-org/Sub-Store#391]
v2.14.444 添加了对 sock 代理的支持，在自己docker 部署的sub-store 更新到最新镜像后，尝试在单条订阅-本地配置写入：
```shell
sock5://ajfwk****:1p83xb****:@69.30.****::5831#webshare家宽
sock5://ajfwk****::1p83x****:@p.webshare.io:80#webshare家宽中转
```
<img width="2509" alt="image" src="https://github.com/user-attachments/assets/5e5dd51d-b04a-4fe6-b79c-2288853af8b6" />

点击即使预览并无有效内容

<img width="424" alt="image" src="https://github.com/user-attachments/assets/8950193d-71a5-44e9-be0a-688ef075f27d" />

`{"status":"failed","error":{"code":"INTERNAL_SERVER_ERROR","type":"InternalServerError","message":"Failed to download subscription: webshare家宽","details":"Reason: 订阅 webshare家宽 中不含有效节点"}}`

请问是哪里有误？

**Comment by xream** [comment]
乱写肯定是不行的

```
socks5://ajfwk****:1p83xb****@69.30.****:5831#webshare家宽
socks5://ajfwk****:1p83x****@p.webshare.io:80#webshare家宽中转
```

**Comment by XYZliang** [comment]
> 乱写肯定是不行的
> 
> ```
> socks5://ajfwk****:1p83xb****@69.30.****:5831#webshare家宽
> socks5://ajfwk****:1p83x****@p.webshare.io:80#webshare家宽中转
> ```

socks5://user:pass@ip:port#name
示例不就是这样的么？账号密码本就是乱码，外加隐私处理*

**Comment by xream** [comment]
麻烦自己看清楚

你写的: `sock5://ajfwk****:1p83xb****:@69.30.****::5831#webshare家宽`
应该为: `socks5://ajfwk****:1p83xb****@69.30.****:5831#webshare家宽`

**Comment by XYZliang** [comment]
确实你回复的前一秒才发现，确实是自己手误打错，可以直接回复，没必要`乱写肯定是不行的`

**Comment by xream** [comment]
1. 首先是你自己写错了. 不知道是没看还是没仔细看还是仅仅只是不小心写错了
2. 我第一条回复就已经提供了正确的写法

**Comment by XYZliang** [comment]
抱歉，确实眼瞎了。。
