### ISSUE TITLE
生成的singbox 和clash(mihomo)导入软件后节点不通

### ISSUE THREAD

**Issue by yyqxjwxy** [sub-store-org/Sub-Store#394]
看到实际生成的代码mihomo只有proxies字段，singbox 只有outbounds字段，导入相关的软件后并不能使用和这个原因有关系吗

**Comment by xream** [comment]
感觉无关
以下供参考: 
ℹ️ 生成文件 & 配置

生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)

**Comment by xream** [comment]
Sub-Store 节点转换问题 正确的反馈方式

1. 描述节点能通等某种方案

例如: 订阅直接导入 App A. 此时 App A 中的节点长这样: x

2. Sub-Store 中使用某种输入, 输出为某种, 不通

举例: 使用机场的通用订阅, 默认 user-agent 为 clash.meta, 输出选择 App A. 输出的节点长这样: y

可知 x 和 y 的区别为 z

可能是 Sub-Store 转换的问题

提供复现方式
