### ISSUE TITLE
组合订阅：增加错误过滤功能

### ISSUE THREAD

**Issue by llkeji** [sub-store-org/Sub-Store#396]
例如我有两条单订阅，组合到了一起，a订阅故障，b订阅正常

现在的体现是组合订阅直接无法使用了

期望：组合订阅不受某一单订阅故障所影响，除非都故障

**Comment by xream** [comment]
已有 
<img width="693" alt="image" src="https://github.com/user-attachments/assets/532c2d13-48fc-4735-b2e4-9c81423c35fa" />
