### ISSUE TITLE
请教如何在clash下，能否添加默认的规则

### ISSUE THREAD

**Issue by ashanzzz** [sub-store-org/Sub-Store#397]
连接参数中没有能增加第三方规则的链接，求教如何修改默认的规则，这样导入clash后，就有一个可用的规则了

**Comment by xream** [comment]
若要生成配置. 参考:

ℹ️ 生成文件 & 配置

生成 clash.meta(mihomo) 配置示例 (https://t.me/zhetengsha/1234)

Surfboard 远程托管配置示例 (https://t.me/zhetengsha/1111)

生成 sing-box 配置 (https://t.me/zhetengsha/1070)

生成 sing-box 机场入口+落地节点 代理链 示例 (https://t.me/zhetengsha/1241)
