### ISSUE TITLE
希望通用链接 可以支持传递多个url和clash配置

### ISSUE THREAD

**Issue by llkeji** [sub-store-org/Sub-Store#398]
通用链接 的方式如何传递多个url，以及clash配置

**Comment by xream** [comment]
@llkeji 跟前端多行一样

encodeURIComponent('https://a.com\nhttps://b.com')
->
'https%3A%2F%2Fa.com%0Ahttps%3A%2F%2Fb.com'

所以是

/download/1?target=Surge&url=https%3A%2F%2Fa.com%0Ahttps%3A%2F%2Fb.com

**Comment by llkeji** [comment]
大佬，那个clash配置文件呢，怎么传递？

**Comment by xream** [comment]
@llkeji 没看懂
