### ISSUE TITLE
无法获取self-signed certificate的远程订阅地址内容

### ISSUE THREAD

**Issue by Rick1125** [sub-store-org/Sub-Store#399]
当配置了远程订阅地址中的网站使用了自签名的证书，无法获取地址内容。

错误日志：
[sub-store] ERROR: 使用 HEAD 方法从响应头获取流量信息失败: https://域名.com/vip?token=xxxx, User-Agent: clash, Insecure: false, Proxy: https://substore.onerise.tech: tunneling socket could not be established, cause=self-signed certificate

**Comment by xream** [comment]
远程订阅支持 insecure 不验证服务器证书 <img width="260" alt="image" src="https://github.com/user-attachments/assets/9cf1f6f2-c13c-4bb0-bc54-2156daefa1d1" />
